#!/usr/bin/env python3
"""
build_catalog.py — Nexus AI Orchestration Model :: package catalog/index builder (step 2).

Scans packages/ and emits packages/INDEX.yaml — the "pull catalog": the list of `.pipeline`
packages a host (Nexus) can acquire, with version + a quick component/gate/stage summary.
This is the marketplace/registry index the consumer pulls from (the host still imports +
fingerprints + dedups per CONSUMER_CONTRACT.md).

Usage:
  python3 engine/build_catalog.py
"""
from __future__ import annotations
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from package_pipeline import load_yaml, write_yaml  # reuse

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PKG_DIR = os.path.join(REPO, "packages")


def main():
    entries = []
    if os.path.isdir(PKG_DIR):
        for name in sorted(os.listdir(PKG_DIR)):
            mp = os.path.join(PKG_DIR, name, "pipeline.package.yaml")
            if not os.path.exists(mp):
                continue
            m = load_yaml(mp) or {}
            gates = m.get("gates", []) or []
            entries.append({
                "pipeline_id": m.get("pipeline_id"),
                "name": m.get("name"),
                "package_version": m.get("package_version"),
                "package_schema_version": m.get("package_schema_version"),
                "path": f"packages/{name}",
                "components": len(m.get("components", []) or []),
                "gates_always": sum(1 for g in gates if g.get("set") == "always"),
                "gates_conditional": sum(1 for g in gates if g.get("set") == "conditional"),
                "stages": len(m.get("stages", []) or []),
                "source_commit": (m.get("provenance", {}) or {}).get("source_commit"),
            })

    index = {
        "catalog_id": "nexus_ai_pipeline_package_catalog",
        "catalog_schema_version": "0.1",
        "purpose": ("Pull catalog: the .pipeline packages a host (Nexus) can acquire. "
                    "Generated by engine/build_catalog.py — do not hand-edit."),
        "package_count": len(entries),
        "packages": entries,
    }
    out = os.path.join(PKG_DIR, "INDEX.yaml")
    write_yaml(out, index)

    print(f"[catalog] wrote {os.path.relpath(out, REPO)}  ({len(entries)} package(s))")
    for e in entries:
        print(f"  - {e['pipeline_id']} v{e['package_version']}  "
              f"({e['components']} comp, {e['gates_always']}+{e['gates_conditional']} gate, {e['stages']} stage)"
              f"  -> {e['path']}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
