export type Scenario = 'happy_path' | 'missing_source_refs' | 'fallback_path';

export type HostRequest = {
  requestId: string;
  objective: string;
  sourceRefs: string[];
  scenario: Scenario;
};

export type RuntimeEvent = {
  event: string;
  ref: string;
  reason?: string;
};

export type ProviderRunRequest = {
  runId: string;
  requestRef: string;
  sourceRefs: string[];
  artifactRoot: string;
  fallbackRef: string;
  manualReviewRequired: true;
};

export type CandidateArtifact = {
  kind: 'candidate_patch';
  ref: string;
  root: string;
  summary: string;
  candidateOnly: true;
};

export type NormalizedResult = {
  resultId: string;
  runRef: string;
  status: 'candidate' | 'fallback_used' | 'blocked';
  summary: string;
  sourceRefs: string[];
  artifactRefs: CandidateArtifact[];
  traceRefs: string[];
  reason?: string;
};

export type ReviewDecision = {
  decisionId: string;
  resultRef: string;
  decision: 'accept_candidate' | 'use_fallback' | 'reject_candidate';
  reason: string;
  operatorRef: string;
};

export type ArtifactDisposition = {
  dispositionId: string;
  artifactRef: string;
  disposition: 'accept_after_review' | 'use_fallback_result' | 'reject_candidate';
  decisionRef: string;
  reason: string;
};

export type AcceptedArtifact = {
  artifactId: string;
  sourceCandidateRef: string;
  acceptedBy: string;
  sourceRefs: string[];
  traceRefs: string[];
};

export type VerticalSliceResult = {
  status: 'accepted' | 'blocked' | 'fallback_used';
  hostRequest: HostRequest;
  runRequest?: ProviderRunRequest;
  normalizedResult?: NormalizedResult;
  reviewDecision?: ReviewDecision;
  disposition?: ArtifactDisposition;
  acceptedArtifacts: AcceptedArtifact[];
  events: RuntimeEvent[];
  reason?: string;
};

function event(name: string, ref: string, reason?: string): RuntimeEvent {
  return reason ? { event: name, ref, reason } : { event: name, ref };
}

function hasSourceRefs(sourceRefs: string[]) {
  return sourceRefs.length > 0 && sourceRefs.every((item) => item.trim().length > 0);
}

export function createHostRequest(scenario: Scenario): HostRequest {
  return {
    requestId: `host-request-${scenario}`,
    objective: 'Produce a reviewed candidate artifact through the provider vertical slice.',
    sourceRefs: scenario === 'missing_source_refs' ? [] : ['docs/implementation-phase-plan.md'],
    scenario,
  };
}

export function createRunRequest(hostRequest: HostRequest): ProviderRunRequest | undefined {
  if (!hasSourceRefs(hostRequest.sourceRefs)) return undefined;
  return {
    runId: `run-${hostRequest.requestId}`,
    requestRef: hostRequest.requestId,
    sourceRefs: hostRequest.sourceRefs,
    artifactRoot: 'artifacts/provider-run-candidates/',
    fallbackRef: 'local-controlled-runtime',
    manualReviewRequired: true,
  };
}

export function mockProviderExecute(runRequest: ProviderRunRequest, scenario: Scenario): NormalizedResult {
  const traceRefs = [`trace/${runRequest.runId}`, `trace/${runRequest.runId}/normalized`];

  if (scenario === 'fallback_path') {
    return {
      resultId: `result-${runRequest.runId}`,
      runRef: runRequest.runId,
      status: 'fallback_used',
      summary: 'Provider path returned to local controlled fallback.',
      sourceRefs: runRequest.sourceRefs,
      artifactRefs: [],
      traceRefs: [...traceRefs, `fallback/${runRequest.fallbackRef}`],
      reason: 'Fallback path selected before artifact acceptance.',
    };
  }

  return {
    resultId: `result-${runRequest.runId}`,
    runRef: runRequest.runId,
    status: 'candidate',
    summary: 'Mock provider produced a candidate artifact for operator review.',
    sourceRefs: runRequest.sourceRefs,
    artifactRefs: [
      {
        kind: 'candidate_patch',
        ref: `${runRequest.artifactRoot}candidate.patch`,
        root: runRequest.artifactRoot,
        summary: 'Candidate patch generated by mock provider.',
        candidateOnly: true,
      },
    ],
    traceRefs,
  };
}

export function reviewResult(result: NormalizedResult): ReviewDecision {
  if (result.status === 'fallback_used') {
    return {
      decisionId: `decision-${result.resultId}`,
      resultRef: result.resultId,
      decision: 'use_fallback',
      reason: 'Fallback result remains non-accepted by default.',
      operatorRef: 'operator.local',
    };
  }

  if (result.status === 'blocked') {
    return {
      decisionId: `decision-${result.resultId}`,
      resultRef: result.resultId,
      decision: 'reject_candidate',
      reason: 'Blocked result cannot be accepted.',
      operatorRef: 'operator.local',
    };
  }

  return {
    decisionId: `decision-${result.resultId}`,
    resultRef: result.resultId,
    decision: 'accept_candidate',
    reason: 'Operator accepted candidate after source, trace, and artifact review.',
    operatorRef: 'operator.local',
  };
}

export function createDisposition(result: NormalizedResult, decision: ReviewDecision): ArtifactDisposition | undefined {
  if (decision.decision === 'accept_candidate' && result.artifactRefs.length > 0) {
    return {
      dispositionId: `disposition-${result.resultId}`,
      artifactRef: result.artifactRefs[0].ref,
      disposition: 'accept_after_review',
      decisionRef: decision.decisionId,
      reason: 'Candidate artifact accepted only after operator decision.',
    };
  }

  if (decision.decision === 'use_fallback') {
    return {
      dispositionId: `disposition-${result.resultId}`,
      artifactRef: 'fallback/local-controlled-runtime',
      disposition: 'use_fallback_result',
      decisionRef: decision.decisionId,
      reason: 'Fallback selected without accepted provider artifact.',
    };
  }

  return undefined;
}

export function commitAcceptedArtifact(result: NormalizedResult, decision: ReviewDecision, disposition?: ArtifactDisposition): AcceptedArtifact[] {
  if (result.status !== 'candidate') return [];
  if (decision.decision !== 'accept_candidate') return [];
  if (!disposition || disposition.disposition !== 'accept_after_review') return [];
  if (result.artifactRefs.length === 0) return [];
  if (!hasSourceRefs(result.sourceRefs)) return [];

  return [
    {
      artifactId: `accepted-${result.artifactRefs[0].ref}`,
      sourceCandidateRef: result.artifactRefs[0].ref,
      acceptedBy: decision.operatorRef,
      sourceRefs: result.sourceRefs,
      traceRefs: result.traceRefs,
    },
  ];
}

export function runProviderVerticalSlice(scenario: Scenario): VerticalSliceResult {
  const hostRequest = createHostRequest(scenario);
  const events: RuntimeEvent[] = [event('host_request_created', hostRequest.requestId)];
  const runRequest = createRunRequest(hostRequest);

  if (!runRequest) {
    const reason = 'Source refs are required before provider execution.';
    return {
      status: 'blocked',
      hostRequest,
      acceptedArtifacts: [],
      events: [...events, event('provider_run_blocked', hostRequest.requestId, reason)],
      reason,
    };
  }

  events.push(event('provider_run_prepared', runRequest.runId));
  const normalizedResult = mockProviderExecute(runRequest, scenario);
  events.push(event('provider_result_normalized', normalizedResult.resultId));
  const reviewDecision = reviewResult(normalizedResult);
  events.push(event('review_decision_recorded', reviewDecision.decisionId));
  const disposition = createDisposition(normalizedResult, reviewDecision);
  if (disposition) events.push(event('artifact_disposition_recorded', disposition.dispositionId));
  const acceptedArtifacts = commitAcceptedArtifact(normalizedResult, reviewDecision, disposition);

  if (acceptedArtifacts.length > 0) {
    events.push(event('accepted_artifact_recorded', acceptedArtifacts[0].artifactId));
    return { status: 'accepted', hostRequest, runRequest, normalizedResult, reviewDecision, disposition, acceptedArtifacts, events };
  }

  if (normalizedResult.status === 'fallback_used') {
    events.push(event('fallback_recorded', runRequest.fallbackRef, normalizedResult.reason));
    return { status: 'fallback_used', hostRequest, runRequest, normalizedResult, reviewDecision, disposition, acceptedArtifacts, events, reason: normalizedResult.reason };
  }

  return { status: 'blocked', hostRequest, runRequest, normalizedResult, reviewDecision, disposition, acceptedArtifacts, events, reason: 'No accepted artifact was produced.' };
}
