import { useMemo, useState } from 'react';
import { Boxes, CheckCircle2, Clipboard, Download, FileJson, Layers, Search, ShieldAlert, ShieldCheck, Users, Wrench } from 'lucide-react';
import macroData from '../registry/macro-pipelines.json';
import microData from '../registry/micro-pipelines.json';
import microExtraData from '../registry/micro-pipelines-extra.json';
import profilesData from '../registry/agent-profiles.json';
import profilesExtraData from '../registry/agent-profiles-extra.json';
import gatesData from '../registry/gates.json';
import packsData from '../registry/example-capability-packs.json';
import packsExtraData from '../registry/capability-packs-extra.json';

type Macro = { id: string; title: string };
type Micro = { id: string; title: string; parent_macro?: string; required_profiles?: string[]; required_gates?: string[] };
type Profile = { id: string; title: string; family?: string };
type Gate = { id: string; title: string; severity?: string };
type Pack = { pack_id: string; type?: string; status?: string; summary: string; for_intents?: string[]; macro_pipeline?: string; micro_pipelines?: string[]; profiles?: string[]; skills?: string[]; tools?: string[]; quality_gates?: string[]; memory_policy?: string; context_policy?: string };
type Form = { pack_id: string; status: string; summary: string; intents: string; macro: string; micro: string[]; profiles: string[]; gates: string[]; skills: string; tools: string; memory: string; context: string };

const macros = (macroData as { macro_pipelines: Macro[] }).macro_pipelines ?? [];
const micros = [...((microData as { micro_pipelines: Micro[] }).micro_pipelines ?? []), ...((microExtraData as { micro_pipelines: Micro[] }).micro_pipelines ?? [])];
const profiles = [...((profilesData as { agent_profiles: Profile[] }).agent_profiles ?? []), ...((profilesExtraData as { agent_profiles: Profile[] }).agent_profiles ?? [])];
const gates = (gatesData as { gates: Gate[] }).gates ?? [];
const packs = [...((packsData as { capability_packs: Pack[] }).capability_packs ?? []), ...((packsExtraData as { capability_packs: Pack[] }).capability_packs ?? [])];

const initial: Form = { pack_id: 'new-capability-pack', status: 'draft', summary: 'Describe the outcome, routing logic and usage boundary of this capability pack.', intents: 'custom workflow\nnew capability', macro: macros[0]?.id ?? '', micro: [], profiles: [], gates: [], skills: 'spec-compliance-review\nverification-loop', tools: 'test-runner\ncontext-stats', memory: 'project-decision-memory', context: 'working-set-context' };
const split = (text: string) => text.split(/[\n,]/).map((x) => x.trim()).filter(Boolean);
const flip = (xs: string[], id: string) => xs.includes(id) ? xs.filter((x) => x !== id) : [...xs, id];

function makePack(f: Form): Pack { return { pack_id: f.pack_id.trim(), type: 'capability-pack', status: f.status, summary: f.summary.trim(), for_intents: split(f.intents), macro_pipeline: f.macro, micro_pipelines: f.micro, profiles: f.profiles, skills: split(f.skills), tools: split(f.tools), quality_gates: f.gates, memory_policy: f.memory.trim(), context_policy: f.context.trim() }; }
function validate(pack: Pack) {
  const errors: string[] = [];
  const warnings: string[] = [];
  const knownPack = new Set(packs.map((x) => x.pack_id));
  const knownMacro = new Set(macros.map((x) => x.id));
  const knownMicro = new Set(micros.map((x) => x.id));
  const knownProfile = new Set(profiles.map((x) => x.id));
  const knownGate = new Set(gates.map((x) => x.id));
  if (!pack.pack_id) errors.push('pack_id required');
  if (pack.pack_id && knownPack.has(pack.pack_id)) warnings.push('pack_id already exists');
  if (!pack.summary || pack.summary.length < 30) errors.push('summary too short');
  if (!pack.for_intents?.length) errors.push('intent coverage required');
  if (!pack.macro_pipeline || !knownMacro.has(pack.macro_pipeline)) errors.push('valid macro_pipeline required');
  if (!pack.micro_pipelines?.length) errors.push('at least one micro_pipeline required');
  if (!pack.profiles?.length) errors.push('at least one profile required');
  if (!pack.quality_gates?.length) errors.push('at least one gate required');
  for (const id of pack.micro_pipelines ?? []) if (!knownMicro.has(id)) errors.push(`unknown micro ${id}`);
  for (const id of pack.profiles ?? []) if (!knownProfile.has(id)) errors.push(`unknown profile ${id}`);
  for (const id of pack.quality_gates ?? []) if (!knownGate.has(id)) errors.push(`unknown gate ${id}`);
  if (!pack.skills?.length) warnings.push('skills empty');
  if (!pack.tools?.length) warnings.push('tools empty');
  return { valid: errors.length === 0, errors, warnings, score: Math.max(0, 100 - errors.length * 20 - warnings.length * 7) };
}
function saveFile(name: string, text: string) { const blob = new Blob([text], { type: 'application/json' }); const url = URL.createObjectURL(blob); const a = document.createElement('a'); a.href = url; a.download = name; document.body.appendChild(a); a.click(); a.remove(); URL.revokeObjectURL(url); }
function Badge({ children, tone = 'neutral' }: { children: string | number; tone?: 'neutral' | 'cyan' | 'green' | 'yellow' | 'red' }) { const c = { neutral: 'border-white/10 bg-white/5 text-neutral-300', cyan: 'border-cyan-500/20 bg-cyan-950/20 text-cyan-300', green: 'border-emerald-500/20 bg-emerald-950/20 text-emerald-300', yellow: 'border-yellow-500/20 bg-yellow-950/20 text-yellow-200', red: 'border-red-500/20 bg-red-950/20 text-red-200' }[tone]; return <span className={`rounded-lg border px-2.5 py-1 text-[11px] font-semibold ${c}`}>{children}</span>; }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="block"><div className="mb-2 text-[10px] font-bold uppercase tracking-widest text-neutral-500">{label}</div>{children}</label>; }
function Option({ on, title, sub, click }: { on: boolean; title: string; sub?: string; click: () => void }) { return <button onClick={click} className={`w-full rounded-xl border p-3 text-left transition ${on ? 'border-cyan-500/40 bg-cyan-950/20' : 'border-white/10 bg-black/30 hover:bg-white/5'}`}><div className="flex items-center justify-between gap-3"><div><div className="text-sm font-medium text-white">{title}</div>{sub && <div className="mt-1 text-xs text-neutral-500">{sub}</div>}</div>{on && <CheckCircle2 size={16} className="text-cyan-300" />}</div></button>; }

export default function PackBuilderView() {
  const [form, setForm] = useState<Form>(initial);
  const [q, setQ] = useState('');
  const pack = useMemo(() => makePack(form), [form]);
  const result = useMemo(() => validate(pack), [pack]);
  const json = JSON.stringify(pack, null, 2);
  const templates = packs.filter((p) => !q || `${p.pack_id} ${p.summary}`.toLowerCase().includes(q.toLowerCase()));
  const visibleMicro = micros.filter((m) => !form.macro || m.parent_macro === form.macro || form.micro.includes(m.id));
  const load = (p: Pack) => setForm({ pack_id: `${p.pack_id}-copy`, status: 'draft', summary: p.summary, intents: (p.for_intents ?? []).join('\n'), macro: p.macro_pipeline ?? '', micro: p.micro_pipelines ?? [], profiles: p.profiles ?? [], gates: p.quality_gates ?? [], skills: (p.skills ?? []).join('\n'), tools: (p.tools ?? []).join('\n'), memory: p.memory_policy ?? '', context: p.context_policy ?? '' });
  const infer = () => { const selected = form.micro.map((id) => micros.find((m) => m.id === id)).filter(Boolean) as Micro[]; setForm({ ...form, profiles: Array.from(new Set([...form.profiles, ...selected.flatMap((m) => m.required_profiles ?? [])])), gates: Array.from(new Set([...form.gates, ...selected.flatMap((m) => m.required_gates ?? [])])) }); };

  return <div className="min-h-screen bg-[#050505] px-4 py-8 text-neutral-200 sm:px-6"><div className="mx-auto flex max-w-[1500px] flex-col gap-6"><header className="rounded-2xl border border-white/10 bg-[#0a0a0a] p-6 shadow-2xl"><div className="flex items-center gap-4"><div className="flex h-12 w-12 items-center justify-center rounded-xl bg-cyan-500 text-black"><Boxes size={26} strokeWidth={2.5} /></div><div><h1 className="text-2xl font-semibold tracking-tight text-white">Controlled Pack Builder</h1><p className="mt-1 text-sm text-neutral-400">Create capability pack JSON from controlled registry selections.</p></div></div></header>
    <section className="grid gap-6 xl:grid-cols-[320px_1fr_430px]"><aside className="rounded-2xl border border-white/10 bg-[#0a0a0a] p-5"><div className="mb-4 flex items-center gap-2 text-sm font-semibold text-white"><Search size={18} className="text-cyan-400" />Templates</div><input value={q} onChange={(e) => setQ(e.target.value)} className="mb-4 w-full rounded-xl border border-white/10 bg-black/50 px-4 py-3 text-sm text-neutral-200 outline-none focus:border-cyan-500/50" placeholder="Search packs" /><div className="max-h-[74vh] space-y-2 overflow-auto pr-1">{templates.map((p) => <button key={p.pack_id} onClick={() => load(p)} className="w-full rounded-xl border border-white/10 bg-black/30 p-3 text-left hover:bg-white/5"><div className="text-sm font-medium text-white">{p.pack_id}</div><div className="mt-1 text-xs text-neutral-500">{p.macro_pipeline ?? 'no macro'}</div></button>)}</div></aside>
    <main className="flex flex-col gap-6"><section className="rounded-2xl border border-white/10 bg-[#0a0a0a] p-6"><div className="mb-4 flex items-center gap-2 text-sm font-semibold text-white"><FileJson size={18} className="text-cyan-400" />Identity</div><div className="grid gap-4 md:grid-cols-2"><Field label="pack id"><input value={form.pack_id} onChange={(e) => setForm({ ...form, pack_id: e.target.value })} className="w-full rounded-xl border border-white/10 bg-black/50 px-4 py-3 text-sm text-neutral-200 outline-none focus:border-cyan-500/50" /></Field><Field label="status"><select value={form.status} onChange={(e) => setForm({ ...form, status: e.target.value })} className="w-full rounded-xl border border-white/10 bg-black/50 px-4 py-3 text-sm text-neutral-200 outline-none focus:border-cyan-500/50"><option>draft</option><option>active</option><option>experimental</option><option>deprecated</option></select></Field></div><div className="mt-4"><Field label="summary"><textarea value={form.summary} onChange={(e) => setForm({ ...form, summary: e.target.value })} className="min-h-[90px] w-full rounded-xl border border-white/10 bg-black/50 p-4 text-sm text-neutral-200 outline-none focus:border-cyan-500/50" /></Field></div><div className="mt-4"><Field label="intent coverage"><textarea value={form.intents} onChange={(e) => setForm({ ...form, intents: e.target.value })} className="min-h-[80px] w-full rounded-xl border border-white/10 bg-black/50 p-4 text-sm text-neutral-200 outline-none focus:border-cyan-500/50" /></Field></div></section>
    <section className="rounded-2xl border border-white/10 bg-[#0a0a0a] p-6"><div className="mb-4 flex items-center gap-2 text-sm font-semibold text-white"><Layers size={18} className="text-cyan-400" />Pipeline</div><Field label="macro"><select value={form.macro} onChange={(e) => setForm({ ...form, macro: e.target.value, micro: [] })} className="w-full rounded-xl border border-white/10 bg-black/50 px-4 py-3 text-sm text-neutral-200 outline-none focus:border-cyan-500/50">{macros.map((m) => <option key={m.id} value={m.id}>{m.title} / {m.id}</option>)}</select></Field><div className="mt-5 flex items-center justify-between"><div className="text-[10px] font-bold uppercase tracking-widest text-neutral-500">micro pipelines</div><button onClick={infer} className="rounded-lg border border-cyan-500/20 bg-cyan-950/20 px-3 py-2 text-xs font-semibold text-cyan-300">Infer profiles + gates</button></div><div className="mt-3 grid gap-2 md:grid-cols-2">{visibleMicro.map((m) => <Option key={m.id} on={form.micro.includes(m.id)} title={m.title} sub={m.id} click={() => setForm({ ...form, micro: flip(form.micro, m.id) })} />)}</div></section>
    <section className="grid gap-6 lg:grid-cols-2"><div className="rounded-2xl border border-white/10 bg-[#0a0a0a] p-6"><div className="mb-4 flex items-center gap-2 text-sm font-semibold text-white"><Users size={18} className="text-cyan-400" />Profiles</div><div className="max-h-[460px] space-y-2 overflow-auto pr-1">{profiles.map((p) => <Option key={p.id} on={form.profiles.includes(p.id)} title={p.title} sub={`${p.id} / ${p.family ?? 'profile'}`} click={() => setForm({ ...form, profiles: flip(form.profiles, p.id) })} />)}</div></div><div className="rounded-2xl border border-white/10 bg-[#0a0a0a] p-6"><div className="mb-4 flex items-center gap-2 text-sm font-semibold text-white"><ShieldCheck size={18} className="text-cyan-400" />Gates</div><div className="max-h-[460px] space-y-2 overflow-auto pr-1">{gates.map((g) => <Option key={g.id} on={form.gates.includes(g.id)} title={g.title} sub={`${g.id} / ${g.severity ?? 'gate'}`} click={() => setForm({ ...form, gates: flip(form.gates, g.id) })} />)}</div></div></section>
    <section className="rounded-2xl border border-white/10 bg-[#0a0a0a] p-6"><div className="mb-4 flex items-center gap-2 text-sm font-semibold text-white"><Wrench size={18} className="text-cyan-400" />Skills, tools, policies</div><div className="grid gap-4 md:grid-cols-2"><Field label="skills"><textarea value={form.skills} onChange={(e) => setForm({ ...form, skills: e.target.value })} className="min-h-[105px] w-full rounded-xl border border-white/10 bg-black/50 p-4 text-sm text-neutral-200 outline-none focus:border-cyan-500/50" /></Field><Field label="tools"><textarea value={form.tools} onChange={(e) => setForm({ ...form, tools: e.target.value })} className="min-h-[105px] w-full rounded-xl border border-white/10 bg-black/50 p-4 text-sm text-neutral-200 outline-none focus:border-cyan-500/50" /></Field><Field label="memory policy"><input value={form.memory} onChange={(e) => setForm({ ...form, memory: e.target.value })} className="w-full rounded-xl border border-white/10 bg-black/50 px-4 py-3 text-sm text-neutral-200 outline-none focus:border-cyan-500/50" /></Field><Field label="context policy"><input value={form.context} onChange={(e) => setForm({ ...form, context: e.target.value })} className="w-full rounded-xl border border-white/10 bg-black/50 px-4 py-3 text-sm text-neutral-200 outline-none focus:border-cyan-500/50" /></Field></div></section></main>
    <aside className="flex flex-col gap-6"><section className="rounded-2xl border border-white/10 bg-[#0a0a0a] p-5"><div className="mb-4 flex items-center justify-between"><div className="flex items-center gap-2 text-sm font-semibold text-white"><ShieldAlert size={18} className="text-cyan-400" />Validation</div><Badge tone={result.valid ? 'green' : 'red'}>{result.valid ? 'valid' : 'invalid'}</Badge></div><div className="grid grid-cols-3 gap-3 text-center"><div className="rounded-xl border border-white/10 bg-black/40 p-3"><div className="text-2xl text-white">{result.score}</div><div className="text-[10px] uppercase tracking-widest text-neutral-500">score</div></div><div className="rounded-xl border border-white/10 bg-black/40 p-3"><div className="text-2xl text-white">{result.errors.length}</div><div className="text-[10px] uppercase tracking-widest text-neutral-500">errors</div></div><div className="rounded-xl border border-white/10 bg-black/40 p-3"><div className="text-2xl text-white">{result.warnings.length}</div><div className="text-[10px] uppercase tracking-widest text-neutral-500">warn</div></div></div><div className="mt-4 space-y-2">{result.errors.map((x) => <div key={x} className="rounded-lg border border-red-500/20 bg-red-950/10 p-2 text-xs text-red-100">{x}</div>)}{result.warnings.map((x) => <div key={x} className="rounded-lg border border-yellow-500/20 bg-yellow-950/10 p-2 text-xs text-yellow-100">{x}</div>)}</div></section><section className="rounded-2xl border border-white/10 bg-[#0a0a0a] p-5"><div className="mb-4 flex items-center justify-between"><div className="flex items-center gap-2 text-sm font-semibold text-white"><FileJson size={18} className="text-cyan-400" />Generated JSON</div><div className="flex gap-2"><button onClick={() => void navigator.clipboard.writeText(json)} className="rounded-lg border border-white/10 bg-black/30 p-2 text-neutral-300 hover:text-white"><Clipboard size={14} /></button><button onClick={() => saveFile(`${pack.pack_id || 'capability-pack'}.json`, json)} className="rounded-lg border border-white/10 bg-black/30 p-2 text-neutral-300 hover:text-white"><Download size={14} /></button></div></div><pre className="max-h-[720px] overflow-auto rounded-xl border border-white/10 bg-black/50 p-4 text-xs leading-relaxed text-neutral-300">{json}</pre></section></aside></section></div></div>;
}
