import type {
  AcceptedArtifact,
  ArtifactDisposition,
  CandidateArtifact,
  HostRequest,
  NormalizedResult,
  ProviderRunRequest,
  ReviewDecision,
  Scenario,
  VerticalSliceResult,
} from './contracts/verticalSliceContracts';
import { InMemoryArtifactRegistry } from './runtime/artifactRegistry';
import { RuntimeLog, runtimeRecord } from './runtime/runtimeLog';

export type { AcceptedArtifact, ArtifactDisposition, CandidateArtifact, HostRequest, NormalizedResult, ProviderRunRequest, ReviewDecision, Scenario, VerticalSliceResult };

function hasSourceRefs(sourceRefs: string[]) {
  return sourceRefs.length > 0 && sourceRefs.every((item) => item.trim().length > 0);
}

function scenarioSourceRefs(scenario: Scenario) {
  return scenario === 'missing_source_refs' ? [] : ['docs/implementation-phase-plan.md'];
}

export function createHostRequest(scenario: Scenario): HostRequest {
  return {
    requestId: `host-request-${scenario}`,
    objective: 'Produce a reviewed candidate artifact through the provider vertical slice.',
    sourceRefs: scenarioSourceRefs(scenario),
    scenario,
  };
}

export function createRunRequest(hostRequest: HostRequest): ProviderRunRequest | undefined {
  if (!hasSourceRefs(hostRequest.sourceRefs)) return undefined;
  return {
    runId: `run-${hostRequest.requestId}`,
    requestRef: hostRequest.requestId,
    sourceRefs: hostRequest.sourceRefs,
    artifactRoot: 'artifacts/provider-run-candidates/',
    fallbackRef: 'local-controlled-runtime',
    manualReviewRequired: true,
  };
}

function artifactRefForScenario(runRequest: ProviderRunRequest, scenario: Scenario) {
  return scenario === 'artifact_outside_root' ? 'tmp/outside-root/candidate.patch' : `${runRequest.artifactRoot}candidate.patch`;
}

export function mockProviderExecute(runRequest: ProviderRunRequest, scenario: Scenario): NormalizedResult {
  const traceRefs = [`trace/${runRequest.runId}`, `trace/${runRequest.runId}/normalized`];

  if (scenario === 'fallback_path') {
    return {
      resultId: `result-${runRequest.runId}`,
      runRef: runRequest.runId,
      status: 'fallback_used',
      summary: 'Provider path returned to local controlled fallback.',
      sourceRefs: runRequest.sourceRefs,
      artifactRefs: [],
      traceRefs: [...traceRefs, `fallback/${runRequest.fallbackRef}`],
      reason: 'Fallback path selected before artifact acceptance.',
    };
  }

  return {
    resultId: `result-${runRequest.runId}`,
    runRef: runRequest.runId,
    status: 'candidate',
    summary: 'Mock provider produced a candidate artifact for operator review.',
    sourceRefs: runRequest.sourceRefs,
    artifactRefs: [
      {
        kind: 'candidate_patch',
        ref: artifactRefForScenario(runRequest, scenario),
        root: runRequest.artifactRoot,
        summary: 'Candidate patch generated by mock provider.',
        candidateOnly: true,
      },
    ],
    traceRefs,
  };
}

export function reviewResult(result: NormalizedResult, scenario: Scenario): ReviewDecision {
  if (scenario === 'request_changes_path') {
    return {
      decisionId: `decision-${result.resultId}`,
      resultRef: result.resultId,
      decision: 'request_changes',
      reason: 'Operator requested a revision before any acceptance.',
      operatorRef: 'operator.local',
    };
  }

  if (scenario === 'review_reject_path' || result.status === 'blocked') {
    return {
      decisionId: `decision-${result.resultId}`,
      resultRef: result.resultId,
      decision: 'reject_candidate',
      reason: 'Operator rejected the candidate output.',
      operatorRef: 'operator.local',
    };
  }

  if (result.status === 'fallback_used') {
    return {
      decisionId: `decision-${result.resultId}`,
      resultRef: result.resultId,
      decision: 'use_fallback',
      reason: 'Fallback result remains non-accepted by default.',
      operatorRef: 'operator.local',
    };
  }

  return {
    decisionId: `decision-${result.resultId}`,
    resultRef: result.resultId,
    decision: 'accept_candidate',
    reason: 'Operator accepted candidate after source, trace, and artifact review.',
    operatorRef: scenario === 'missing_operator_ref' ? '' : 'operator.local',
  };
}

export function createDisposition(result: NormalizedResult, decision: ReviewDecision, scenario: Scenario): ArtifactDisposition | undefined {
  if (scenario === 'artifact_without_disposition') return undefined;

  if (decision.decision === 'accept_candidate' && result.artifactRefs.length > 0) {
    return {
      dispositionId: `disposition-${result.resultId}`,
      artifactRef: result.artifactRefs[0].ref,
      disposition: 'accept_after_review',
      decisionRef: decision.decisionId,
      reason: 'Candidate artifact accepted only after operator decision.',
    };
  }

  if (decision.decision === 'use_fallback') {
    return {
      dispositionId: `disposition-${result.resultId}`,
      artifactRef: 'fallback/local-controlled-runtime',
      disposition: 'use_fallback_result',
      decisionRef: decision.decisionId,
      reason: 'Fallback selected without accepted provider artifact.',
    };
  }

  if (decision.decision === 'request_changes' && result.artifactRefs.length > 0) {
    return {
      dispositionId: `disposition-${result.resultId}`,
      artifactRef: result.artifactRefs[0].ref,
      disposition: 'request_revision',
      decisionRef: decision.decisionId,
      reason: 'Candidate artifact needs revision before acceptance.',
    };
  }

  if (decision.decision === 'reject_candidate' && result.artifactRefs.length > 0) {
    return {
      dispositionId: `disposition-${result.resultId}`,
      artifactRef: result.artifactRefs[0].ref,
      disposition: 'reject_candidate',
      decisionRef: decision.decisionId,
      reason: 'Candidate artifact rejected by operator decision.',
    };
  }

  return undefined;
}

export function runProviderVerticalSlice(scenario: Scenario): VerticalSliceResult {
  const registry = new InMemoryArtifactRegistry();
  const log = new RuntimeLog();
  const hostRequest = createHostRequest(scenario);
  log.add(runtimeRecord('host_request_created', hostRequest.requestId));
  const runRequest = createRunRequest(hostRequest);

  if (!runRequest) {
    const reason = 'Source refs are required before provider execution.';
    log.add(runtimeRecord('provider_run_blocked', hostRequest.requestId, reason));
    return {
      status: 'blocked',
      hostRequest,
      acceptedArtifacts: [],
      events: log.snapshot(),
      reason,
    };
  }

  log.add(runtimeRecord('provider_run_prepared', runRequest.runId));
  const normalizedResult = mockProviderExecute(runRequest, scenario);
  registry.recordCandidates(normalizedResult.artifactRefs);
  log.add(runtimeRecord('provider_result_normalized', normalizedResult.resultId));
  const reviewDecision = reviewResult(normalizedResult, scenario);
  log.add(runtimeRecord('review_decision_recorded', reviewDecision.decisionId));
  const disposition = createDisposition(normalizedResult, reviewDecision, scenario);
  if (disposition) log.add(runtimeRecord('artifact_disposition_recorded', disposition.dispositionId));
  const acceptedArtifacts = registry.commitAccepted(normalizedResult, reviewDecision, disposition);

  if (acceptedArtifacts.length > 0) {
    log.add(runtimeRecord('accepted_artifact_recorded', acceptedArtifacts[0].artifactId));
    return { status: 'accepted', hostRequest, runRequest, normalizedResult, reviewDecision, disposition, acceptedArtifacts, events: log.snapshot() };
  }

  if (normalizedResult.status === 'fallback_used') {
    log.add(runtimeRecord('fallback_recorded', runRequest.fallbackRef, normalizedResult.reason));
    return { status: 'fallback_used', hostRequest, runRequest, normalizedResult, reviewDecision, disposition, acceptedArtifacts, events: log.snapshot(), reason: normalizedResult.reason };
  }

  if (reviewDecision.decision === 'request_changes') {
    return { status: 'changes_requested', hostRequest, runRequest, normalizedResult, reviewDecision, disposition, acceptedArtifacts, events: log.snapshot(), reason: 'Operator requested changes.' };
  }

  if (reviewDecision.decision === 'reject_candidate') {
    return { status: 'rejected', hostRequest, runRequest, normalizedResult, reviewDecision, disposition, acceptedArtifacts, events: log.snapshot(), reason: 'Operator rejected candidate.' };
  }

  return { status: 'blocked', hostRequest, runRequest, normalizedResult, reviewDecision, disposition, acceptedArtifacts, events: log.snapshot(), reason: 'No accepted artifact was produced.' };
}
