import type {
  AcceptedArtifact,
  ArtifactDisposition,
  CandidateArtifact,
  HostRequest,
  NormalizedResult,
  ProviderRunRequest,
  ReasonCode,
  ReviewDecision,
  Scenario,
  SliceRunner,
  VerticalSliceResult,
} from './contracts/verticalSliceContracts';
import { InMemoryArtifactRegistry } from './runtime/artifactRegistry';
import { RuntimeLog, runtimeRecord } from './runtime/runtimeLog';
import { StateFlow } from './runtime/stateFlow';

export type { AcceptedArtifact, ArtifactDisposition, CandidateArtifact, HostRequest, NormalizedResult, ProviderRunRequest, ReasonCode, ReviewDecision, Scenario, SliceRunner, VerticalSliceResult };

function hasSourceRefs(sourceRefs: string[]) {
  return sourceRefs.length > 0 && sourceRefs.every((item) => item.trim().length > 0);
}

function scenarioSourceRefs(scenario: Scenario) {
  return scenario === 'missing_source_refs' ? [] : ['docs/implementation-phase-plan.md'];
}

export function createHostRequest(scenario: Scenario): HostRequest {
  return {
    requestId: `host-request-${scenario}`,
    objective: 'Produce a reviewed candidate artifact through the provider vertical slice.',
    sourceRefs: scenarioSourceRefs(scenario),
    scenario,
  };
}

export function createRunRequest(hostRequest: HostRequest): ProviderRunRequest | undefined {
  if (!hasSourceRefs(hostRequest.sourceRefs)) return undefined;
  return {
    runId: `run-${hostRequest.requestId}`,
    requestRef: hostRequest.requestId,
    sourceRefs: hostRequest.sourceRefs,
    artifactRoot: 'artifacts/provider-run-candidates/',
    fallbackRef: 'local-controlled-runtime',
    manualReviewRequired: true,
  };
}

function artifactRefForScenario(runRequest: ProviderRunRequest, scenario: Scenario) {
  return scenario === 'artifact_outside_root' ? 'tmp/outside-root/candidate.patch' : `${runRequest.artifactRoot}candidate.patch`;
}

export function mockProviderExecute(runRequest: ProviderRunRequest, scenario: Scenario): NormalizedResult {
  const traceRefs = [`trace/${runRequest.runId}`, `trace/${runRequest.runId}/normalized`];

  if (scenario === 'fallback_path') {
    return {
      resultId: `result-${runRequest.runId}`,
      runRef: runRequest.runId,
      status: 'fallback_used',
      summary: 'Provider path returned to local controlled fallback.',
      sourceRefs: runRequest.sourceRefs,
      artifactRefs: [],
      traceRefs: [...traceRefs, `fallback/${runRequest.fallbackRef}`],
      reason: 'Fallback path selected before artifact acceptance.',
      reasonCode: 'FALLBACK_SELECTED',
    };
  }

  return {
    resultId: `result-${runRequest.runId}`,
    runRef: runRequest.runId,
    status: 'candidate',
    summary: 'Mock provider produced a candidate artifact for operator review.',
    sourceRefs: runRequest.sourceRefs,
    artifactRefs: [
      {
        kind: 'candidate_patch',
        ref: artifactRefForScenario(runRequest, scenario),
        root: runRequest.artifactRoot,
        summary: 'Candidate patch generated by mock provider.',
        candidateOnly: true,
      },
    ],
    traceRefs,
    reasonCode: scenario === 'artifact_outside_root' ? 'ARTIFACT_OUTSIDE_ROOT' : 'NONE',
  };
}

export const defaultSliceRunner: SliceRunner = {
  runnerRef: 'mock-slice-runner-v1',
  run: mockProviderExecute,
};

export function reviewResult(result: NormalizedResult, scenario: Scenario): ReviewDecision {
  if (scenario === 'request_changes_path') {
    return {
      decisionId: `decision-${result.resultId}`,
      resultRef: result.resultId,
      decision: 'request_changes',
      reason: 'Operator requested a revision before any acceptance.',
      reasonCode: 'CHANGES_REQUESTED',
      operatorRef: 'operator.local',
    };
  }

  if (scenario === 'review_reject_path' || result.status === 'blocked') {
    return {
      decisionId: `decision-${result.resultId}`,
      resultRef: result.resultId,
      decision: 'reject_candidate',
      reason: 'Operator rejected the candidate output.',
      reasonCode: 'REVIEW_REJECTED',
      operatorRef: 'operator.local',
    };
  }

  if (result.status === 'fallback_used') {
    return {
      decisionId: `decision-${result.resultId}`,
      resultRef: result.resultId,
      decision: 'use_fallback',
      reason: 'Fallback result remains non-accepted by default.',
      reasonCode: 'FALLBACK_SELECTED',
      operatorRef: 'operator.local',
    };
  }

  return {
    decisionId: `decision-${result.resultId}`,
    resultRef: result.resultId,
    decision: 'accept_candidate',
    reason: 'Operator accepted candidate after source, trace, and artifact review.',
    reasonCode: scenario === 'missing_operator_ref' ? 'MISSING_OPERATOR_REF' : 'NONE',
    operatorRef: scenario === 'missing_operator_ref' ? '' : 'operator.local',
  };
}

export function createDisposition(result: NormalizedResult, decision: ReviewDecision, scenario: Scenario): ArtifactDisposition | undefined {
  if (scenario === 'artifact_without_disposition') return undefined;

  if (decision.decision === 'accept_candidate' && result.artifactRefs.length > 0) {
    return {
      dispositionId: `disposition-${result.resultId}`,
      artifactRef: result.artifactRefs[0].ref,
      disposition: 'accept_after_review',
      decisionRef: decision.decisionId,
      reason: 'Candidate artifact accepted only after operator decision.',
      reasonCode: result.reasonCode ?? decision.reasonCode,
    };
  }

  if (decision.decision === 'use_fallback') {
    return {
      dispositionId: `disposition-${result.resultId}`,
      artifactRef: 'fallback/local-controlled-runtime',
      disposition: 'use_fallback_result',
      decisionRef: decision.decisionId,
      reason: 'Fallback selected without accepted provider artifact.',
      reasonCode: 'FALLBACK_SELECTED',
    };
  }

  if (decision.decision === 'request_changes' && result.artifactRefs.length > 0) {
    return {
      dispositionId: `disposition-${result.resultId}`,
      artifactRef: result.artifactRefs[0].ref,
      disposition: 'request_revision',
      decisionRef: decision.decisionId,
      reason: 'Candidate artifact needs revision before acceptance.',
      reasonCode: 'CHANGES_REQUESTED',
    };
  }

  if (decision.decision === 'reject_candidate' && result.artifactRefs.length > 0) {
    return {
      dispositionId: `disposition-${result.resultId}`,
      artifactRef: result.artifactRefs[0].ref,
      disposition: 'reject_candidate',
      decisionRef: decision.decisionId,
      reason: 'Candidate artifact rejected by operator decision.',
      reasonCode: 'REVIEW_REJECTED',
    };
  }

  return undefined;
}

function blockedReasonCode(scenario: Scenario, result?: NormalizedResult, decision?: ReviewDecision, disposition?: ArtifactDisposition): ReasonCode {
  if (scenario === 'missing_source_refs') return 'MISSING_SOURCE_REFS';
  if (scenario === 'artifact_without_disposition' && !disposition) return 'MISSING_DISPOSITION';
  if (scenario === 'missing_operator_ref' && !decision?.operatorRef.trim()) return 'MISSING_OPERATOR_REF';
  if (scenario === 'artifact_outside_root' || result?.reasonCode === 'ARTIFACT_OUTSIDE_ROOT') return 'ARTIFACT_OUTSIDE_ROOT';
  return 'NO_ACCEPTED_ARTIFACT';
}

export function runProviderVerticalSlice(scenario: Scenario, runner: SliceRunner = defaultSliceRunner): VerticalSliceResult {
  const registry = new InMemoryArtifactRegistry();
  const log = new RuntimeLog();
  const flow = new StateFlow();
  const hostRequest = createHostRequest(scenario);
  log.add(runtimeRecord('host_request_created', hostRequest.requestId));
  const runRequest = createRunRequest(hostRequest);

  if (!runRequest) {
    const reason = 'Source refs are required before provider execution.';
    const reasonCode: ReasonCode = 'MISSING_SOURCE_REFS';
    flow.move('blocked');
    log.add(runtimeRecord('provider_run_blocked', hostRequest.requestId, reason, reasonCode));
    return {
      status: 'blocked',
      hostRequest,
      acceptedArtifacts: [],
      events: log.snapshot(),
      stateHistory: flow.history(),
      runnerRef: runner.runnerRef,
      reason,
      reasonCode,
    };
  }

  flow.move('prepared');
  log.add(runtimeRecord('provider_run_prepared', runRequest.runId));
  flow.move('running');
  const normalizedResult = runner.run(runRequest, scenario);
  registry.recordCandidates(normalizedResult.artifactRefs);

  if (normalizedResult.status === 'fallback_used') {
    const reasonCode: ReasonCode = 'FALLBACK_SELECTED';
    flow.move('fallback_used');
    log.add(runtimeRecord('provider_result_normalized', normalizedResult.resultId, normalizedResult.reason, reasonCode));
    const reviewDecision = reviewResult(normalizedResult, scenario);
    const disposition = createDisposition(normalizedResult, reviewDecision, scenario);
    log.add(runtimeRecord('review_decision_recorded', reviewDecision.decisionId, reviewDecision.reason, reviewDecision.reasonCode));
    if (disposition) log.add(runtimeRecord('artifact_disposition_recorded', disposition.dispositionId, disposition.reason, disposition.reasonCode));
    log.add(runtimeRecord('fallback_recorded', runRequest.fallbackRef, normalizedResult.reason, reasonCode));
    return { status: 'fallback_used', hostRequest, runRequest, normalizedResult, reviewDecision, disposition, acceptedArtifacts: [], events: log.snapshot(), stateHistory: flow.history(), runnerRef: runner.runnerRef, reason: normalizedResult.reason, reasonCode };
  }

  flow.move('normalized');
  log.add(runtimeRecord('provider_result_normalized', normalizedResult.resultId, normalizedResult.reason, normalizedResult.reasonCode));
  const reviewDecision = reviewResult(normalizedResult, scenario);
  flow.move('reviewed');
  log.add(runtimeRecord('review_decision_recorded', reviewDecision.decisionId, reviewDecision.reason, reviewDecision.reasonCode));
  const disposition = createDisposition(normalizedResult, reviewDecision, scenario);
  if (disposition) {
    flow.move('disposed');
    log.add(runtimeRecord('artifact_disposition_recorded', disposition.dispositionId, disposition.reason, disposition.reasonCode));
  }
  const acceptedArtifacts = registry.commitAccepted(normalizedResult, reviewDecision, disposition);

  if (acceptedArtifacts.length > 0) {
    flow.move('accepted');
    log.add(runtimeRecord('accepted_artifact_recorded', acceptedArtifacts[0].artifactId));
    return { status: 'accepted', hostRequest, runRequest, normalizedResult, reviewDecision, disposition, acceptedArtifacts, events: log.snapshot(), stateHistory: flow.history(), runnerRef: runner.runnerRef, reasonCode: 'NONE' };
  }

  if (reviewDecision.decision === 'request_changes') {
    const reasonCode: ReasonCode = 'CHANGES_REQUESTED';
    flow.move('changes_requested');
    return { status: 'changes_requested', hostRequest, runRequest, normalizedResult, reviewDecision, disposition, acceptedArtifacts, events: log.snapshot(), stateHistory: flow.history(), runnerRef: runner.runnerRef, reason: 'Operator requested changes.', reasonCode };
  }

  if (reviewDecision.decision === 'reject_candidate') {
    const reasonCode: ReasonCode = 'REVIEW_REJECTED';
    flow.move('rejected');
    return { status: 'rejected', hostRequest, runRequest, normalizedResult, reviewDecision, disposition, acceptedArtifacts, events: log.snapshot(), stateHistory: flow.history(), runnerRef: runner.runnerRef, reason: 'Operator rejected candidate.', reasonCode };
  }

  const reasonCode = blockedReasonCode(scenario, normalizedResult, reviewDecision, disposition);
  flow.move('blocked');
  return { status: 'blocked', hostRequest, runRequest, normalizedResult, reviewDecision, disposition, acceptedArtifacts, events: log.snapshot(), stateHistory: flow.history(), runnerRef: runner.runnerRef, reason: 'No accepted artifact was produced.', reasonCode };
}
