import { useMemo, useState } from 'react';
import { Activity, Cpu, FileJson, Network, PlayCircle, RotateCcw, Settings2 } from 'lucide-react';
import {
  applyRuntimeEventsToRunnerState,
  buildRuntimeAdapterRequest,
  summarizeRuntimeAdapterResponse,
  type EvidenceState,
  type RuntimeAdapterRequest,
  type RuntimeAdapterResponse,
  type TaskPacket,
  type WorkStatus,
} from './runtimeAdapter.ts';
import {
  createRuntimeAdapterProviderRegistry,
  dispatchRuntimeAdapterRequest,
  getRuntimeAdapterProvider,
  type RuntimeAdapterProviderHealth,
} from './runtimeAdapterProvider.ts';
import { mockRuntimeAdapterProvider } from './runtimeAdapters/mockRuntimeAdapterProvider.ts';
import { createHttpRuntimeAdapterProvider } from './runtimeAdapters/httpRuntimeAdapterProvider.ts';

type DispatchMode = RuntimeAdapterRequest['dispatch']['mode'];
type DispatchPriority = RuntimeAdapterRequest['dispatch']['priority'];

const defaultAdapterConfig = {
  providerId: 'mock',
  dispatchMode: 'mock' as DispatchMode,
  endpointUrl: '',
  healthcheckUrl: '',
  authToken: '',
  timeoutMs: 30000,
  maxRetries: 1,
  retryDelayMs: 250,
  retryOnStatuses: '408,409,425,429,500,502,503,504',
  targetWorker: 'nexus-worker/mock-adapter',
  priority: 'normal' as DispatchPriority,
  callbackUrl: 'capability-os://runtime/callbacks',
  idempotencyKey: '',
  operatorNotes: 'Generated by Task Runner adapter simulation.',
};

function Badge({ children, tone = 'neutral' }: { children: React.ReactNode; tone?: 'neutral' | 'cyan' | 'green' | 'yellow' | 'red' }) {
  const cls = {
    neutral: 'border-white/10 bg-white/5 text-neutral-300',
    cyan: 'border-cyan-500/20 bg-cyan-950/20 text-cyan-300',
    green: 'border-emerald-500/20 bg-emerald-950/20 text-emerald-300',
    yellow: 'border-yellow-500/20 bg-yellow-950/10 text-yellow-200',
    red: 'border-red-500/20 bg-red-950/10 text-red-200',
  }[tone];
  return <span className={`rounded-md border px-2 py-1 text-[11px] ${cls}`}>{children}</span>;
}

function Field({ label, children }: { label: string; children: React.ReactNode }) {
  return (
    <label className="block">
      <span className="mb-1 block text-[10px] font-semibold uppercase tracking-widest text-neutral-500">{label}</span>
      {children}
    </label>
  );
}

const inputClass = 'w-full rounded-lg border border-white/10 bg-black/40 px-3 py-2 text-xs text-neutral-200 outline-none placeholder:text-neutral-600 focus:border-cyan-500/40';

function downloadJson(filename: string, payload: unknown) {
  const blob = new Blob([JSON.stringify(payload, null, 2)], { type: 'application/json' });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement('a');
  anchor.href = url;
  anchor.download = filename;
  document.body.appendChild(anchor);
  anchor.click();
  anchor.remove();
  URL.revokeObjectURL(url);
}

function parseRetryStatuses(value: string) {
  return value
    .split(',')
    .map((item) => Number(item.trim()))
    .filter((item) => Number.isInteger(item) && item >= 100 && item <= 599);
}

function clampNumber(value: number, min: number, max: number) {
  if (!Number.isFinite(value)) return min;
  return Math.min(max, Math.max(min, value));
}

type Props = {
  packet: TaskPacket;
  statuses: Record<string, WorkStatus>;
  evidence: EvidenceState;
  onApplyRuntimeState: (next: { statuses: Record<string, WorkStatus>; evidence: EvidenceState }) => void;
};

export default function RuntimeAdapterPanel({ packet, statuses, evidence, onApplyRuntimeState }: Props) {
  const [providerId, setProviderId] = useState(defaultAdapterConfig.providerId);
  const [dispatchMode, setDispatchMode] = useState<DispatchMode>(defaultAdapterConfig.dispatchMode);
  const [endpointUrl, setEndpointUrl] = useState(defaultAdapterConfig.endpointUrl);
  const [healthcheckUrl, setHealthcheckUrl] = useState(defaultAdapterConfig.healthcheckUrl);
  const [authToken, setAuthToken] = useState(defaultAdapterConfig.authToken);
  const [timeoutMs, setTimeoutMs] = useState(defaultAdapterConfig.timeoutMs);
  const [maxRetries, setMaxRetries] = useState(defaultAdapterConfig.maxRetries);
  const [retryDelayMs, setRetryDelayMs] = useState(defaultAdapterConfig.retryDelayMs);
  const [retryOnStatuses, setRetryOnStatuses] = useState(defaultAdapterConfig.retryOnStatuses);
  const [targetWorker, setTargetWorker] = useState(defaultAdapterConfig.targetWorker);
  const [priority, setPriority] = useState<DispatchPriority>(defaultAdapterConfig.priority);
  const [callbackUrl, setCallbackUrl] = useState(defaultAdapterConfig.callbackUrl);
  const [idempotencyKey, setIdempotencyKey] = useState(defaultAdapterConfig.idempotencyKey);
  const [operatorNotes, setOperatorNotes] = useState(defaultAdapterConfig.operatorNotes);
  const [request, setRequest] = useState<RuntimeAdapterRequest | null>(null);
  const [response, setResponse] = useState<RuntimeAdapterResponse | null>(null);
  const [lastAppliedEventCount, setLastAppliedEventCount] = useState(0);
  const [dispatchError, setDispatchError] = useState<string | null>(null);
  const [healthResult, setHealthResult] = useState<RuntimeAdapterProviderHealth | null>(null);
  const [isDispatching, setIsDispatching] = useState(false);
  const [isCheckingHealth, setIsCheckingHealth] = useState(false);

  const retryStatuses = useMemo(() => parseRetryStatuses(retryOnStatuses), [retryOnStatuses]);
  const providerRegistry = useMemo(() => createRuntimeAdapterProviderRegistry([
    mockRuntimeAdapterProvider,
    createHttpRuntimeAdapterProvider({
      endpoint_url: endpointUrl.trim(),
      healthcheck_url: healthcheckUrl.trim() || undefined,
      auth_token: authToken.trim() || undefined,
      timeout_ms: clampNumber(timeoutMs, 1000, 600000),
      retry_policy: {
        max_retries: clampNumber(maxRetries, 0, 10),
        retry_delay_ms: clampNumber(retryDelayMs, 0, 30000),
        retry_on_statuses: retryStatuses,
      },
    }),
  ]), [authToken, endpointUrl, healthcheckUrl, maxRetries, retryDelayMs, retryStatuses, timeoutMs]);

  const provider = useMemo(() => getRuntimeAdapterProvider(providerRegistry, providerId), [providerId, providerRegistry]);
  const summary = useMemo(() => (response ? summarizeRuntimeAdapterResponse(response) : null), [response]);
  const isHttpProvider = provider.mode === 'http';
  const effectiveHealthUrl = healthcheckUrl.trim() || endpointUrl.trim();

  const buildConfiguredRequest = () => {
    const nextRequest = buildRuntimeAdapterRequest(packet, dispatchMode);
    return {
      ...nextRequest,
      dispatch: {
        ...nextRequest.dispatch,
        mode: dispatchMode,
        target_worker: targetWorker.trim() || nextRequest.dispatch.target_worker,
        priority,
        idempotency_key: idempotencyKey.trim() || nextRequest.dispatch.idempotency_key,
        callback_url: callbackUrl.trim() || nextRequest.dispatch.callback_url,
        timeout_seconds: Math.ceil(clampNumber(timeoutMs, 1000, 600000) / 1000),
      },
      operator_notes: operatorNotes.trim() || undefined,
    } satisfies RuntimeAdapterRequest;
  };

  const dispatchAdapter = async () => {
    setIsDispatching(true);
    setDispatchError(null);
    const nextRequest = buildConfiguredRequest();
    setRequest(nextRequest);
    try {
      const nextResponse = await dispatchRuntimeAdapterRequest(provider, nextRequest);
      const patch = applyRuntimeEventsToRunnerState(statuses, evidence, nextResponse.events);
      setResponse(nextResponse);
      setLastAppliedEventCount(patch.applied_events.length);
      onApplyRuntimeState({ statuses: patch.statuses, evidence: patch.evidence });
    } catch (error) {
      setResponse(null);
      setLastAppliedEventCount(0);
      setDispatchError(error instanceof Error ? error.message : 'Runtime adapter dispatch failed.');
    } finally {
      setIsDispatching(false);
    }
  };

  const checkHealth = async () => {
    if (!provider.healthCheck) return;
    setIsCheckingHealth(true);
    setDispatchError(null);
    try {
      const result = await provider.healthCheck();
      setHealthResult(result);
    } catch (error) {
      setHealthResult({
        ok: false,
        provider_id: provider.id,
        status: 'failed',
        message: error instanceof Error ? error.message : 'Runtime adapter health check failed.',
        checked_at: new Date().toISOString(),
      });
    } finally {
      setIsCheckingHealth(false);
    }
  };

  const resetConfig = () => {
    setProviderId(defaultAdapterConfig.providerId);
    setDispatchMode(defaultAdapterConfig.dispatchMode);
    setEndpointUrl(defaultAdapterConfig.endpointUrl);
    setHealthcheckUrl(defaultAdapterConfig.healthcheckUrl);
    setAuthToken(defaultAdapterConfig.authToken);
    setTimeoutMs(defaultAdapterConfig.timeoutMs);
    setMaxRetries(defaultAdapterConfig.maxRetries);
    setRetryDelayMs(defaultAdapterConfig.retryDelayMs);
    setRetryOnStatuses(defaultAdapterConfig.retryOnStatuses);
    setTargetWorker(defaultAdapterConfig.targetWorker);
    setPriority(defaultAdapterConfig.priority);
    setCallbackUrl(defaultAdapterConfig.callbackUrl);
    setIdempotencyKey(defaultAdapterConfig.idempotencyKey);
    setOperatorNotes(defaultAdapterConfig.operatorNotes);
    setHealthResult(null);
    setDispatchError(null);
  };

  return (
    <section className="rounded-2xl border border-cyan-500/20 bg-cyan-950/10 p-6">
      <div className="mb-4 flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between">
        <div>
          <div className="mb-1 flex items-center gap-2 text-sm font-semibold text-cyan-100"><Network size={18} />Runtime Adapter Bridge</div>
          <p className="text-sm text-neutral-400">Configure provider, dispatch mode, endpoint, retry policy and callback metadata before generating the runtime adapter request.</p>
        </div>
        <div className="flex flex-wrap items-center gap-2">
          <button onClick={resetConfig} className="flex items-center gap-2 rounded-lg border border-white/10 bg-black/30 px-3 py-2 text-xs font-semibold text-neutral-300 hover:text-white">
            <RotateCcw size={14} /> Reset config
          </button>
          <button onClick={() => void checkHealth()} disabled={isCheckingHealth || !provider.healthCheck} className="flex items-center gap-2 rounded-lg border border-white/10 bg-black/30 px-3 py-2 text-xs font-semibold text-neutral-300 hover:text-white disabled:cursor-not-allowed disabled:opacity-50">
            <Activity size={14} /> {isCheckingHealth ? 'Checking...' : 'Health check'}
          </button>
          <button onClick={() => void dispatchAdapter()} disabled={isDispatching} className="flex items-center gap-2 rounded-lg border border-cyan-500/30 bg-cyan-950/30 px-3 py-2 text-xs font-semibold text-cyan-200 hover:bg-cyan-900/30 disabled:cursor-not-allowed disabled:opacity-50">
            <PlayCircle size={14} /> {isDispatching ? 'Dispatching...' : 'Dispatch adapter'}
          </button>
        </div>
      </div>

      <div className="mb-4 grid gap-3 lg:grid-cols-3">
        <Field label="Provider">
          <select value={providerId} onChange={(event) => {
            setProviderId(event.target.value);
            setDispatchMode(event.target.value === 'mock' ? 'mock' : 'real');
            setHealthResult(null);
          }} className={inputClass}>
            {Object.values(providerRegistry).map((item) => <option key={item.id} value={item.id}>{item.label}</option>)}
          </select>
        </Field>
        <Field label="Dispatch mode">
          <select value={dispatchMode} onChange={(event) => setDispatchMode(event.target.value as DispatchMode)} className={inputClass}>
            <option value="dry_run">dry_run</option>
            <option value="mock">mock</option>
            <option value="real">real</option>
          </select>
        </Field>
        <Field label="Priority">
          <select value={priority} onChange={(event) => setPriority(event.target.value as DispatchPriority)} className={inputClass}>
            <option value="low">low</option>
            <option value="normal">normal</option>
            <option value="high">high</option>
          </select>
        </Field>
      </div>

      <div className="mb-4 rounded-xl border border-white/10 bg-black/30 p-4">
        <div className="mb-3 flex flex-wrap items-center gap-2">
          <Badge tone={provider.mode === 'mock' ? 'green' : provider.mode === 'http' ? 'yellow' : 'cyan'}>{provider.id}</Badge>
          <Badge>{provider.mode}</Badge>
          <Badge tone={dispatchMode === 'real' ? 'yellow' : dispatchMode === 'mock' ? 'green' : 'cyan'}>{dispatchMode}</Badge>
          {isHttpProvider && !endpointUrl.trim() && <Badge tone="red">endpoint required for dispatch</Badge>}
          {isHttpProvider && effectiveHealthUrl && <Badge tone="cyan">health url configured</Badge>}
        </div>
        <p className="text-sm text-neutral-400">{provider.description}</p>
      </div>

      <div className="mb-4 grid gap-3 lg:grid-cols-2">
        <div className="rounded-xl border border-white/10 bg-black/30 p-4">
          <div className="mb-3 flex items-center gap-2 text-xs font-semibold text-cyan-100"><Settings2 size={14} />HTTP provider config</div>
          <div className="grid gap-3 md:grid-cols-2">
            <Field label="endpoint_url">
              <input value={endpointUrl} onChange={(event) => setEndpointUrl(event.target.value)} placeholder="https://runtime.local/runtime/dispatch" className={inputClass} />
            </Field>
            <Field label="healthcheck_url">
              <input value={healthcheckUrl} onChange={(event) => setHealthcheckUrl(event.target.value)} placeholder="defaults to endpoint_url" className={inputClass} />
            </Field>
            <Field label="timeout_ms">
              <input type="number" min={1000} max={600000} value={timeoutMs} onChange={(event) => setTimeoutMs(Number(event.target.value))} className={inputClass} />
            </Field>
            <Field label="auth token">
              <input value={authToken} onChange={(event) => setAuthToken(event.target.value)} placeholder="optional bearer token" type="password" className={inputClass} />
            </Field>
            <Field label="max_retries">
              <input type="number" min={0} max={10} value={maxRetries} onChange={(event) => setMaxRetries(Number(event.target.value))} className={inputClass} />
            </Field>
            <Field label="retry_delay_ms">
              <input type="number" min={0} max={30000} value={retryDelayMs} onChange={(event) => setRetryDelayMs(Number(event.target.value))} className={inputClass} />
            </Field>
            <div className="md:col-span-2">
              <Field label="retry_on_statuses">
                <input value={retryOnStatuses} onChange={(event) => setRetryOnStatuses(event.target.value)} placeholder="408,429,500,502,503,504" className={inputClass} />
              </Field>
              <div className="mt-2 text-[11px] text-neutral-500">Parsed: {retryStatuses.length ? retryStatuses.join(', ') : 'none'}</div>
            </div>
          </div>
        </div>

        <div className="rounded-xl border border-white/10 bg-black/30 p-4">
          <div className="mb-3 flex items-center gap-2 text-xs font-semibold text-cyan-100"><Cpu size={14} />Runtime request dispatch config</div>
          <div className="grid gap-3 md:grid-cols-2">
            <Field label="target_worker">
              <input value={targetWorker} onChange={(event) => setTargetWorker(event.target.value)} className={inputClass} />
            </Field>
            <Field label="idempotency_key">
              <input value={idempotencyKey} onChange={(event) => setIdempotencyKey(event.target.value)} placeholder="default generated from objective" className={inputClass} />
            </Field>
            <div className="md:col-span-2">
              <Field label="callback_url">
                <input value={callbackUrl} onChange={(event) => setCallbackUrl(event.target.value)} className={inputClass} />
              </Field>
            </div>
            <div className="md:col-span-2">
              <Field label="operator_notes">
                <textarea value={operatorNotes} onChange={(event) => setOperatorNotes(event.target.value)} rows={3} className={inputClass} />
              </Field>
            </div>
          </div>
        </div>
      </div>

      {healthResult && (
        <div className={`mb-4 rounded-xl border p-4 text-sm ${healthResult.ok ? 'border-emerald-500/20 bg-emerald-950/10 text-emerald-100' : 'border-yellow-500/20 bg-yellow-950/10 text-yellow-100'}`}>
          <div className="mb-2 flex flex-wrap gap-2">
            <Badge tone={healthResult.ok ? 'green' : healthResult.status === 'unconfigured' ? 'yellow' : 'red'}>{healthResult.status}</Badge>
            <Badge>{healthResult.provider_id}</Badge>
            <Badge>{new Date(healthResult.checked_at).toLocaleTimeString()}</Badge>
          </div>
          {healthResult.message}
        </div>
      )}

      {dispatchError && <div className="mb-4 rounded-xl border border-red-500/20 bg-red-950/10 p-4 text-sm text-red-100">{dispatchError}</div>}

      <div className="grid gap-3 md:grid-cols-4">
        <div className="rounded-xl border border-white/10 bg-black/30 p-4 text-center"><div className="text-2xl text-white">{summary?.event_count ?? '-'}</div><div className="text-[10px] uppercase tracking-widest text-neutral-500">events</div></div>
        <div className="rounded-xl border border-white/10 bg-black/30 p-4 text-center"><div className="text-2xl text-white">{summary?.accepted ? 'yes' : response ? 'no' : '-'}</div><div className="text-[10px] uppercase tracking-widest text-neutral-500">accepted</div></div>
        <div className="rounded-xl border border-white/10 bg-black/30 p-4 text-center"><div className="text-2xl text-white">{summary?.event_types.length ?? '-'}</div><div className="text-[10px] uppercase tracking-widest text-neutral-500">event types</div></div>
        <div className="rounded-xl border border-white/10 bg-black/30 p-4 text-center"><div className="text-2xl text-white">{lastAppliedEventCount || '-'}</div><div className="text-[10px] uppercase tracking-widest text-neutral-500">applied</div></div>
      </div>

      {request && (
        <div className="mt-4 rounded-xl border border-white/10 bg-black/30 p-4">
          <div className="mb-3 flex flex-wrap gap-2">
            <Badge tone="cyan">request configured</Badge>
            <Badge>{request.dispatch.mode}</Badge>
            <Badge>{request.dispatch.priority}</Badge>
            <Badge>{request.dispatch.timeout_seconds}s</Badge>
            <Badge>{request.dispatch.target_worker}</Badge>
          </div>
          <div className="text-xs text-neutral-500">callback: {request.dispatch.callback_url}</div>
        </div>
      )}

      {summary && (
        <div className="mt-4 rounded-xl border border-white/10 bg-black/30 p-4">
          <div className="mb-3 flex flex-wrap gap-2">
            <Badge tone={summary.accepted ? 'green' : 'red'}>{summary.status}</Badge>
            <Badge tone="cyan">{summary.job_id}</Badge>
            <Badge>{summary.target_worker}</Badge>
          </div>
          <div className="flex flex-wrap gap-2">{summary.event_types.map((type) => <Badge key={type} tone="yellow">{type}</Badge>)}</div>
        </div>
      )}

      {(request || response) && (
        <div className="mt-4 flex flex-wrap gap-2">
          {request && <button onClick={() => downloadJson('runtime-adapter-request.json', request)} className="flex items-center gap-2 rounded-lg border border-white/10 bg-black/30 px-3 py-2 text-xs font-semibold text-neutral-300 hover:text-white"><FileJson size={14} />Export request</button>}
          {response && <button onClick={() => downloadJson('runtime-adapter-response.json', response)} className="flex items-center gap-2 rounded-lg border border-white/10 bg-black/30 px-3 py-2 text-xs font-semibold text-neutral-300 hover:text-white"><FileJson size={14} />Export response</button>}
        </div>
      )}

      <div className="mt-4 grid gap-3 md:grid-cols-2">
        <div className="rounded-xl border border-white/10 bg-black/30 p-4 text-sm text-neutral-400"><Cpu size={16} className="mb-2 text-cyan-400" />Mock provider runs in-process; HTTP provider now uses the panel config for endpoint, timeout, retry and auth boundaries.</div>
        <div className="rounded-xl border border-white/10 bg-black/30 p-4 text-sm text-neutral-400"><Network size={16} className="mb-2 text-cyan-400" />Dispatch metadata is written into the runtime adapter request before events update Runner step status and gate evidence.</div>
      </div>
    </section>
  );
}
