import { useMemo, useState } from 'react';
import { Activity, Cpu, FileJson, Network, PlayCircle, RotateCcw, Settings2 } from 'lucide-react';
import {
  applyRuntimeEventsToRunnerState,
  buildMockRuntimeCallbackPayload,
  buildRuntimeAdapterRequest,
  ingestRuntimeCallback,
  runtimeEventKey,
  summarizeRuntimeAdapterResponse,
  validateRuntimeCallbackPayload,
  type EvidenceState,
  type RuntimeAdapterRequest,
  type RuntimeAdapterResponse,
  type RuntimeBridgeEvent,
  type RuntimeCallbackPayload,
  type TaskPacket,
  type WorkStatus,
} from './runtimeAdapter.ts';
import {
  createRuntimeAdapterProviderRegistry,
  dispatchRuntimeAdapterRequest,
  getRuntimeAdapterProvider,
  type RuntimeAdapterProviderHealth,
} from './runtimeAdapterProvider.ts';
import { mockRuntimeAdapterProvider } from './runtimeAdapters/mockRuntimeAdapterProvider.ts';
import { createHttpRuntimeAdapterProvider } from './runtimeAdapters/httpRuntimeAdapterProvider.ts';
import { buildRuntimeArtifactRegistryFromEvents, summarizeRuntimeArtifactRegistry } from './runtimeArtifactRegistry.ts';
import { buildHardenedReviewReport } from './reviewReportHardening.ts';
import { buildHardenedMemoryContextPackets } from './memoryContextHardening.ts';

type DispatchMode = RuntimeAdapterRequest['dispatch']['mode'];
type DispatchPriority = RuntimeAdapterRequest['dispatch']['priority'];

const defaultAdapterConfig = {
  providerId: 'mock',
  dispatchMode: 'mock' as DispatchMode,
  endpointUrl: '',
  healthcheckUrl: '',
  authToken: '',
  timeoutMs: 30000,
  maxRetries: 1,
  retryDelayMs: 250,
  retryOnStatuses: '408,409,425,429,500,502,503,504',
  targetWorker: 'nexus-worker/mock-adapter',
  priority: 'normal' as DispatchPriority,
  callbackUrl: 'capability-os://runtime/callbacks',
  idempotencyKey: '',
  operatorNotes: 'Generated by Task Runner adapter simulation.',
};

function Badge({ children, tone = 'neutral' }: { children: React.ReactNode; tone?: 'neutral' | 'cyan' | 'green' | 'yellow' | 'red' }) {
  const cls = {
    neutral: 'border-white/10 bg-white/5 text-neutral-300',
    cyan: 'border-cyan-500/20 bg-cyan-950/20 text-cyan-300',
    green: 'border-emerald-500/20 bg-emerald-950/20 text-emerald-300',
    yellow: 'border-yellow-500/20 bg-yellow-950/10 text-yellow-200',
    red: 'border-red-500/20 bg-red-950/10 text-red-200',
  }[tone];
  return <span className={`rounded-md border px-2 py-1 text-[11px] ${cls}`}>{children}</span>;
}

function Field({ label, children }: { label: string; children: React.ReactNode }) {
  return (
    <label className="block">
      <span className="mb-1 block text-[10px] font-semibold uppercase tracking-widest text-neutral-500">{label}</span>
      {children}
    </label>
  );
}

function DetailRow({ label, value }: { label: string; value: React.ReactNode }) {
  return (
    <div className="flex items-start justify-between gap-3 border-b border-white/5 py-2 last:border-b-0">
      <span className="text-[10px] font-semibold uppercase tracking-widest text-neutral-500">{label}</span>
      <span className="max-w-[70%] break-all text-right text-xs text-neutral-200">{value || '-'}</span>
    </div>
  );
}

const inputClass = 'w-full rounded-lg border border-white/10 bg-black/40 px-3 py-2 text-xs text-neutral-200 outline-none placeholder:text-neutral-600 focus:border-cyan-500/40';

function downloadJson(filename: string, payload: unknown) {
  const blob = new Blob([JSON.stringify(payload, null, 2)], { type: 'application/json' });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement('a');
  anchor.href = url;
  anchor.download = filename;
  document.body.appendChild(anchor);
  anchor.click();
  anchor.remove();
  URL.revokeObjectURL(url);
}

function parseRetryStatuses(value: string) {
  return value
    .split(',')
    .map((item) => Number(item.trim()))
    .filter((item) => Number.isInteger(item) && item >= 100 && item <= 599);
}

function clampNumber(value: number, min: number, max: number) {
  if (!Number.isFinite(value)) return min;
  return Math.min(max, Math.max(min, value));
}

function stableSlug(input: string) {
  return input.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '').slice(0, 60) || 'item';
}

function allRuntimeEvents(response: RuntimeAdapterResponse | null, callbackPayload: RuntimeCallbackPayload | null): RuntimeBridgeEvent[] {
  return [
    ...(response?.events ?? []),
    ...(callbackPayload?.events ?? []),
  ];
}

function buildControlledWorkerManifestPreview(packet: TaskPacket) {
  return {
    packet_type: 'nexus.controlled_worker_manifest',
    version: '0.1',
    manifest_id: `panel-preview-${stableSlug(packet.objective)}`,
    actions: [
      ...packet.work_order.map((step) => ({
        action_id: `write-${stableSlug(step.id)}`,
        action_kind: 'write_step_artifact',
        step_id: step.id,
        output_kind: step.expected_outputs?.[0] ?? 'controlled_step_artifact',
      })),
      {
        action_id: 'write-manifest-summary',
        action_kind: 'write_manifest_summary',
        output_kind: 'controlled_manifest_summary',
      },
    ],
  };
}

type Props = {
  packet: TaskPacket;
  statuses: Record<string, WorkStatus>;
  evidence: EvidenceState;
  onApplyRuntimeState: (next: { statuses: Record<string, WorkStatus>; evidence: EvidenceState }) => void;
};

export default function RuntimeAdapterPanel({ packet, statuses, evidence, onApplyRuntimeState }: Props) {
  const [providerId, setProviderId] = useState(defaultAdapterConfig.providerId);
  const [dispatchMode, setDispatchMode] = useState<DispatchMode>(defaultAdapterConfig.dispatchMode);
  const [endpointUrl, setEndpointUrl] = useState(defaultAdapterConfig.endpointUrl);
  const [healthcheckUrl, setHealthcheckUrl] = useState(defaultAdapterConfig.healthcheckUrl);
  const [authToken, setAuthToken] = useState(defaultAdapterConfig.authToken);
  const [timeoutMs, setTimeoutMs] = useState(defaultAdapterConfig.timeoutMs);
  const [maxRetries, setMaxRetries] = useState(defaultAdapterConfig.maxRetries);
  const [retryDelayMs, setRetryDelayMs] = useState(defaultAdapterConfig.retryDelayMs);
  const [retryOnStatuses, setRetryOnStatuses] = useState(defaultAdapterConfig.retryOnStatuses);
  const [targetWorker, setTargetWorker] = useState(defaultAdapterConfig.targetWorker);
  const [priority, setPriority] = useState<DispatchPriority>(defaultAdapterConfig.priority);
  const [callbackUrl, setCallbackUrl] = useState(defaultAdapterConfig.callbackUrl);
  const [idempotencyKey, setIdempotencyKey] = useState(defaultAdapterConfig.idempotencyKey);
  const [operatorNotes, setOperatorNotes] = useState(defaultAdapterConfig.operatorNotes);
  const [request, setRequest] = useState<RuntimeAdapterRequest | null>(null);
  const [response, setResponse] = useState<RuntimeAdapterResponse | null>(null);
  const [callbackPayload, setCallbackPayload] = useState<RuntimeCallbackPayload | null>(null);
  const [callbackSequence, setCallbackSequence] = useState(0);
  const [seenEventKeys, setSeenEventKeys] = useState<string[]>([]);
  const [lastAppliedEventCount, setLastAppliedEventCount] = useState(0);
  const [lastCallbackAcceptedCount, setLastCallbackAcceptedCount] = useState(0);
  const [lastCallbackDuplicateCount, setLastCallbackDuplicateCount] = useState(0);
  const [totalCallbackAcceptedCount, setTotalCallbackAcceptedCount] = useState(0);
  const [dispatchError, setDispatchError] = useState<string | null>(null);
  const [callbackError, setCallbackError] = useState<string | null>(null);
  const [healthResult, setHealthResult] = useState<RuntimeAdapterProviderHealth | null>(null);
  const [isDispatching, setIsDispatching] = useState(false);
  const [isCheckingHealth, setIsCheckingHealth] = useState(false);

  const retryStatuses = useMemo(() => parseRetryStatuses(retryOnStatuses), [retryOnStatuses]);
  const providerRegistry = useMemo(() => createRuntimeAdapterProviderRegistry([
    mockRuntimeAdapterProvider,
    createHttpRuntimeAdapterProvider({
      endpoint_url: endpointUrl.trim(),
      healthcheck_url: healthcheckUrl.trim() || undefined,
      auth_token: authToken.trim() || undefined,
      timeout_ms: clampNumber(timeoutMs, 1000, 600000),
      retry_policy: {
        max_retries: clampNumber(maxRetries, 0, 10),
        retry_delay_ms: clampNumber(retryDelayMs, 0, 30000),
        retry_on_statuses: retryStatuses,
      },
    }),
  ]), [authToken, endpointUrl, healthcheckUrl, maxRetries, retryDelayMs, retryStatuses, timeoutMs]);

  const provider = useMemo(() => getRuntimeAdapterProvider(providerRegistry, providerId), [providerId, providerRegistry]);
  const summary = useMemo(() => (response ? summarizeRuntimeAdapterResponse(response) : null), [response]);
  const runtimeEvents = useMemo(() => allRuntimeEvents(response, callbackPayload), [callbackPayload, response]);
  const artifactRegistry = useMemo(() => buildRuntimeArtifactRegistryFromEvents(runtimeEvents), [runtimeEvents]);
  const artifactSummary = useMemo(() => summarizeRuntimeArtifactRegistry(artifactRegistry), [artifactRegistry]);
  const reviewPreview = useMemo(() => buildHardenedReviewReport(packet, statuses, evidence, artifactRegistry), [artifactRegistry, evidence, packet, statuses]);
  const memoryContextPreview = useMemo(() => buildHardenedMemoryContextPackets(packet, reviewPreview, { artifactRegistry, maxContextItems: 8 }), [artifactRegistry, packet, reviewPreview]);
  const controlledManifestPreview = useMemo(() => buildControlledWorkerManifestPreview(packet), [packet]);
  const isHttpProvider = provider.mode === 'http';
  const effectiveHealthUrl = healthcheckUrl.trim() || endpointUrl.trim();

  const jobStatePreview = useMemo(() => {
    if (!response) return null;
    const lastRuntimeEvent = runtimeEvents[runtimeEvents.length - 1];
    return {
      job_id: response.job.job_id,
      request_id: response.request_id,
      provider_id: provider.id,
      target_worker: response.job.target_worker,
      status: response.status,
      started_at: response.job.started_at,
      last_event_at: lastRuntimeEvent?.timestamp ?? response.job.started_at,
      event_count: runtimeEvents.length,
      artifact_count: artifactRegistry.artifacts.length,
      repeated_artifact_count: artifactRegistry.repeated.length,
      error_count: response.error ? 1 : 0,
      callbacks: {
        received: callbackPayload ? callbackSequence : 0,
        accepted_events: totalCallbackAcceptedCount,
        duplicate_events: lastCallbackDuplicateCount,
        last_received_at: callbackPayload?.received_at,
      },
      seen_event_key_count: seenEventKeys.length,
    };
  }, [artifactRegistry.artifacts.length, artifactRegistry.repeated.length, callbackPayload, callbackSequence, lastCallbackDuplicateCount, provider.id, response, runtimeEvents, seenEventKeys.length, totalCallbackAcceptedCount]);

  const buildConfiguredRequest = () => {
    const nextRequest = buildRuntimeAdapterRequest(packet, dispatchMode);
    return {
      ...nextRequest,
      dispatch: {
        ...nextRequest.dispatch,
        mode: dispatchMode,
        target_worker: targetWorker.trim() || nextRequest.dispatch.target_worker,
        priority,
        idempotency_key: idempotencyKey.trim() || nextRequest.dispatch.idempotency_key,
        callback_url: callbackUrl.trim() || nextRequest.dispatch.callback_url,
        timeout_seconds: Math.ceil(clampNumber(timeoutMs, 1000, 600000) / 1000),
      },
      operator_notes: operatorNotes.trim() || undefined,
    } satisfies RuntimeAdapterRequest;
  };

  const dispatchAdapter = async () => {
    setIsDispatching(true);
    setDispatchError(null);
    setCallbackError(null);
    const nextRequest = buildConfiguredRequest();
    setRequest(nextRequest);
    try {
      const nextResponse = await dispatchRuntimeAdapterRequest(provider, nextRequest);
      const patch = applyRuntimeEventsToRunnerState(statuses, evidence, nextResponse.events);
      setResponse(nextResponse);
      setCallbackPayload(null);
      setCallbackSequence(0);
      setSeenEventKeys(nextResponse.events.map(runtimeEventKey));
      setLastCallbackAcceptedCount(0);
      setLastCallbackDuplicateCount(0);
      setTotalCallbackAcceptedCount(0);
      setLastAppliedEventCount(patch.applied_events.length);
      onApplyRuntimeState({ statuses: patch.statuses, evidence: patch.evidence });
    } catch (error) {
      setResponse(null);
      setCallbackPayload(null);
      setSeenEventKeys([]);
      setLastAppliedEventCount(0);
      setLastCallbackAcceptedCount(0);
      setLastCallbackDuplicateCount(0);
      setTotalCallbackAcceptedCount(0);
      setDispatchError(error instanceof Error ? error.message : 'Runtime adapter dispatch failed.');
    } finally {
      setIsDispatching(false);
    }
  };

  const ingestCallbackPayload = (payload: RuntimeCallbackPayload, advanceSequence: boolean) => {
    const validation = validateRuntimeCallbackPayload(payload);
    if (!validation.valid || !validation.payload) {
      setCallbackError(validation.errors.join('; '));
      return;
    }
    const result = ingestRuntimeCallback(statuses, evidence, validation.payload, seenEventKeys);
    setCallbackPayload(validation.payload);
    setSeenEventKeys(result.seen_event_keys);
    setLastAppliedEventCount(result.applied_events.length);
    setLastCallbackAcceptedCount(result.accepted_events.length);
    setLastCallbackDuplicateCount(result.duplicate_events.length);
    setTotalCallbackAcceptedCount((current) => current + result.accepted_events.length);
    setCallbackError(null);
    if (advanceSequence) setCallbackSequence((current) => current + 1);
    onApplyRuntimeState({ statuses: result.statuses, evidence: result.evidence });
  };

  const simulateCallback = () => {
    if (!request || !response) {
      setCallbackError('Dispatch a runtime adapter request before simulating callbacks.');
      return;
    }
    ingestCallbackPayload(buildMockRuntimeCallbackPayload(request, response, callbackSequence), true);
  };

  const replayLastCallback = () => {
    if (!callbackPayload) {
      setCallbackError('No callback payload has been ingested yet.');
      return;
    }
    ingestCallbackPayload(callbackPayload, false);
  };

  const checkHealth = async () => {
    if (!provider.healthCheck) return;
    setIsCheckingHealth(true);
    setDispatchError(null);
    try {
      const result = await provider.healthCheck();
      setHealthResult(result);
    } catch (error) {
      setHealthResult({
        ok: false,
        provider_id: provider.id,
        status: 'failed',
        message: error instanceof Error ? error.message : 'Runtime adapter health check failed.',
        checked_at: new Date().toISOString(),
      });
    } finally {
      setIsCheckingHealth(false);
    }
  };

  const resetConfig = () => {
    setProviderId(defaultAdapterConfig.providerId);
    setDispatchMode(defaultAdapterConfig.dispatchMode);
    setEndpointUrl(defaultAdapterConfig.endpointUrl);
    setHealthcheckUrl(defaultAdapterConfig.healthcheckUrl);
    setAuthToken(defaultAdapterConfig.authToken);
    setTimeoutMs(defaultAdapterConfig.timeoutMs);
    setMaxRetries(defaultAdapterConfig.maxRetries);
    setRetryDelayMs(defaultAdapterConfig.retryDelayMs);
    setRetryOnStatuses(defaultAdapterConfig.retryOnStatuses);
    setTargetWorker(defaultAdapterConfig.targetWorker);
    setPriority(defaultAdapterConfig.priority);
    setCallbackUrl(defaultAdapterConfig.callbackUrl);
    setIdempotencyKey(defaultAdapterConfig.idempotencyKey);
    setOperatorNotes(defaultAdapterConfig.operatorNotes);
    setHealthResult(null);
    setDispatchError(null);
    setCallbackError(null);
  };

  return (
    <section className="rounded-2xl border border-cyan-500/20 bg-cyan-950/10 p-6">
      <div className="mb-4 flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between">
        <div>
          <div className="mb-1 flex items-center gap-2 text-sm font-semibold text-cyan-100"><Network size={18} />Runtime Adapter Bridge</div>
          <p className="text-sm text-neutral-400">Configure provider, dispatch mode, endpoint, retry policy and callback metadata before generating the runtime adapter request.</p>
        </div>
        <div className="flex flex-wrap items-center gap-2">
          <button onClick={resetConfig} className="flex items-center gap-2 rounded-lg border border-white/10 bg-black/30 px-3 py-2 text-xs font-semibold text-neutral-300 hover:text-white">
            <RotateCcw size={14} /> Reset config
          </button>
          <button onClick={() => void checkHealth()} disabled={isCheckingHealth || !provider.healthCheck} className="flex items-center gap-2 rounded-lg border border-white/10 bg-black/30 px-3 py-2 text-xs font-semibold text-neutral-300 hover:text-white disabled:cursor-not-allowed disabled:opacity-50">
            <Activity size={14} /> {isCheckingHealth ? 'Checking...' : 'Health check'}
          </button>
          <button onClick={() => void dispatchAdapter()} disabled={isDispatching} className="flex items-center gap-2 rounded-lg border border-cyan-500/30 bg-cyan-950/30 px-3 py-2 text-xs font-semibold text-cyan-200 hover:bg-cyan-900/30 disabled:cursor-not-allowed disabled:opacity-50">
            <PlayCircle size={14} /> {isDispatching ? 'Dispatching...' : 'Dispatch configured adapter'}
          </button>
        </div>
      </div>

      <div className="mb-4 grid gap-3 lg:grid-cols-3">
        <Field label="Provider">
          <select value={providerId} onChange={(event) => {
            setProviderId(event.target.value);
            setDispatchMode(event.target.value === 'mock' ? 'mock' : 'real');
            setHealthResult(null);
          }} className={inputClass}>
            {Object.values(providerRegistry).map((item) => <option key={item.id} value={item.id}>{item.label}</option>)}
          </select>
        </Field>
        <Field label="Dispatch mode">
          <select value={dispatchMode} onChange={(event) => setDispatchMode(event.target.value as DispatchMode)} className={inputClass}>
            <option value="dry_run">dry_run</option>
            <option value="mock">mock</option>
            <option value="real">real</option>
          </select>
        </Field>
        <Field label="Priority">
          <select value={priority} onChange={(event) => setPriority(event.target.value as DispatchPriority)} className={inputClass}>
            <option value="low">low</option>
            <option value="normal">normal</option>
            <option value="high">high</option>
          </select>
        </Field>
      </div>

      <div className="mb-4 rounded-xl border border-white/10 bg-black/30 p-4">
        <div className="mb-3 flex flex-wrap items-center gap-2">
          <Badge tone={provider.mode === 'mock' ? 'green' : provider.mode === 'http' ? 'yellow' : 'cyan'}>{provider.id}</Badge>
          <Badge>{provider.mode}</Badge>
          <Badge tone={dispatchMode === 'real' ? 'yellow' : dispatchMode === 'mock' ? 'green' : 'cyan'}>{dispatchMode}</Badge>
          {isHttpProvider && !endpointUrl.trim() && <Badge tone="red">endpoint required for dispatch</Badge>}
          {isHttpProvider && effectiveHealthUrl && <Badge tone="cyan">health url configured</Badge>}
        </div>
        <p className="text-sm text-neutral-400">{provider.description}</p>
      </div>

      <div className="mb-4 grid gap-3 lg:grid-cols-2">
        <div className="rounded-xl border border-white/10 bg-black/30 p-4">
          <div className="mb-3 flex items-center gap-2 text-xs font-semibold text-cyan-100"><Settings2 size={14} />HTTP provider config</div>
          <div className="grid gap-3 md:grid-cols-2">
            <Field label="endpoint_url">
              <input value={endpointUrl} onChange={(event) => setEndpointUrl(event.target.value)} placeholder="https://runtime.local/runtime/dispatch" className={inputClass} />
            </Field>
            <Field label="healthcheck_url">
              <input value={healthcheckUrl} onChange={(event) => setHealthcheckUrl(event.target.value)} placeholder="defaults to endpoint_url" className={inputClass} />
            </Field>
            <Field label="timeout_ms">
              <input type="number" min={1000} max={600000} value={timeoutMs} onChange={(event) => setTimeoutMs(Number(event.target.value))} className={inputClass} />
            </Field>
            <Field label="auth token">
              <input value={authToken} onChange={(event) => setAuthToken(event.target.value)} placeholder="optional bearer token" type="password" className={inputClass} />
            </Field>
            <Field label="max_retries">
              <input type="number" min={0} max={10} value={maxRetries} onChange={(event) => setMaxRetries(Number(event.target.value))} className={inputClass} />
            </Field>
            <Field label="retry_delay_ms">
              <input type="number" min={0} max={30000} value={retryDelayMs} onChange={(event) => setRetryDelayMs(Number(event.target.value))} className={inputClass} />
            </Field>
            <div className="md:col-span-2">
              <Field label="retry_on_statuses">
                <input value={retryOnStatuses} onChange={(event) => setRetryOnStatuses(event.target.value)} placeholder="408,429,500,502,503,504" className={inputClass} />
              </Field>
              <div className="mt-2 text-[11px] text-neutral-500">Parsed: {retryStatuses.length ? retryStatuses.join(', ') : 'none'}</div>
            </div>
          </div>
        </div>

        <div className="rounded-xl border border-white/10 bg-black/30 p-4">
          <div className="mb-3 flex items-center gap-2 text-xs font-semibold text-cyan-100"><Cpu size={14} />Runtime request dispatch config</div>
          <div className="grid gap-3 md:grid-cols-2">
            <Field label="target_worker">
              <input value={targetWorker} onChange={(event) => setTargetWorker(event.target.value)} className={inputClass} />
            </Field>
            <Field label="idempotency_key">
              <input value={idempotencyKey} onChange={(event) => setIdempotencyKey(event.target.value)} placeholder="default generated from objective" className={inputClass} />
            </Field>
            <div className="md:col-span-2">
              <Field label="callback_url">
                <input value={callbackUrl} onChange={(event) => setCallbackUrl(event.target.value)} className={inputClass} />
              </Field>
            </div>
            <div className="md:col-span-2">
              <Field label="operator_notes">
                <textarea value={operatorNotes} onChange={(event) => setOperatorNotes(event.target.value)} rows={3} className={inputClass} />
              </Field>
            </div>
          </div>
        </div>
      </div>

      {healthResult && (
        <div className={`mb-4 rounded-xl border p-4 text-sm ${healthResult.ok ? 'border-emerald-500/20 bg-emerald-950/10 text-emerald-100' : 'border-yellow-500/20 bg-yellow-950/10 text-yellow-100'}`}>
          <div className="mb-2 flex flex-wrap gap-2">
            <Badge tone={healthResult.ok ? 'green' : healthResult.status === 'unconfigured' ? 'yellow' : 'red'}>{healthResult.status}</Badge>
            <Badge>{healthResult.provider_id}</Badge>
            <Badge>{new Date(healthResult.checked_at).toLocaleTimeString()}</Badge>
          </div>
          {healthResult.message}
          <div className="mt-2 text-[11px] text-neutral-400">Health check does not dispatch work.</div>
        </div>
      )}

      {dispatchError && <div className="mb-4 rounded-xl border border-red-500/20 bg-red-950/10 p-4 text-sm text-red-100">{dispatchError}</div>}
      {callbackError && <div className="mb-4 rounded-xl border border-red-500/20 bg-red-950/10 p-4 text-sm text-red-100">{callbackError}</div>}

      <div className="grid gap-3 md:grid-cols-6">
        <div className="rounded-xl border border-white/10 bg-black/30 p-4 text-center"><div className="text-2xl text-white">{summary?.event_count ?? '-'}</div><div className="text-[10px] uppercase tracking-widest text-neutral-500">initial events</div></div>
        <div className="rounded-xl border border-white/10 bg-black/30 p-4 text-center"><div className="text-2xl text-white">{summary?.accepted ? 'yes' : response ? 'no' : '-'}</div><div className="text-[10px] uppercase tracking-widest text-neutral-500">accepted</div></div>
        <div className="rounded-xl border border-white/10 bg-black/30 p-4 text-center"><div className="text-2xl text-white">{summary?.event_types.length ?? '-'}</div><div className="text-[10px] uppercase tracking-widest text-neutral-500">event types</div></div>
        <div className="rounded-xl border border-white/10 bg-black/30 p-4 text-center"><div className="text-2xl text-white">{lastAppliedEventCount || '-'}</div><div className="text-[10px] uppercase tracking-widest text-neutral-500">last applied</div></div>
        <div className="rounded-xl border border-white/10 bg-black/30 p-4 text-center"><div className="text-2xl text-white">{totalCallbackAcceptedCount || '-'}</div><div className="text-[10px] uppercase tracking-widest text-neutral-500">callback accepted</div></div>
        <div className="rounded-xl border border-white/10 bg-black/30 p-4 text-center"><div className="text-2xl text-white">{lastCallbackDuplicateCount || '-'}</div><div className="text-[10px] uppercase tracking-widest text-neutral-500">duplicates</div></div>
      </div>

      {request && (
        <div className="mt-4 rounded-xl border border-white/10 bg-black/30 p-4">
          <div className="mb-3 flex flex-wrap gap-2">
            <Badge tone="cyan">request configured</Badge>
            <Badge>{request.dispatch.mode}</Badge>
            <Badge>{request.dispatch.priority}</Badge>
            <Badge>{request.dispatch.timeout_seconds}s</Badge>
            <Badge>{request.dispatch.target_worker}</Badge>
          </div>
          <div className="text-xs text-neutral-500">callback: {request.dispatch.callback_url}</div>
        </div>
      )}

      {summary && (
        <div className="mt-4 rounded-xl border border-white/10 bg-black/30 p-4">
          <div className="mb-3 flex flex-wrap gap-2">
            <Badge tone={summary.accepted ? 'green' : 'red'}>{summary.status}</Badge>
            <Badge tone="cyan">{summary.job_id}</Badge>
            <Badge>{summary.target_worker}</Badge>
          </div>
          <div className="flex flex-wrap gap-2">{summary.event_types.map((type) => <Badge key={type} tone="yellow">{type}</Badge>)}</div>
        </div>
      )}

      {jobStatePreview && (
        <div className="mt-4 rounded-xl border border-white/10 bg-black/30 p-4">
          <div className="mb-3 flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between">
            <div>
              <div className="mb-1 text-xs font-semibold text-cyan-100">Job State</div>
              <p className="text-xs text-neutral-500">First-class job state view derived from the verified runtime adapter response and callback ingest path.</p>
            </div>
            <button onClick={() => downloadJson('runtime-job-state.json', jobStatePreview)} className="flex items-center gap-2 rounded-lg border border-white/10 bg-black/30 px-3 py-2 text-xs font-semibold text-neutral-300 hover:text-white"><FileJson size={14} />Export job state</button>
          </div>
          <div className="grid gap-x-6 md:grid-cols-2">
            <DetailRow label="job_id" value={jobStatePreview.job_id} />
            <DetailRow label="request_id" value={jobStatePreview.request_id} />
            <DetailRow label="provider_id" value={jobStatePreview.provider_id} />
            <DetailRow label="target_worker" value={jobStatePreview.target_worker} />
            <DetailRow label="status" value={jobStatePreview.status} />
            <DetailRow label="last_event_at" value={jobStatePreview.last_event_at} />
            <DetailRow label="event_count" value={jobStatePreview.event_count} />
            <DetailRow label="artifact_count" value={`${jobStatePreview.artifact_count} unique / ${jobStatePreview.repeated_artifact_count} repeated`} />
            <DetailRow label="error_count" value={jobStatePreview.error_count} />
            <DetailRow label="callback counters" value={`${jobStatePreview.callbacks.accepted_events} accepted / ${jobStatePreview.callbacks.duplicate_events} duplicate`} />
          </div>
        </div>
      )}

      <div className="mt-4 grid gap-3 xl:grid-cols-2">
        <div className="rounded-xl border border-white/10 bg-black/30 p-4">
          <div className="mb-3 flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between">
            <div>
              <div className="mb-1 text-xs font-semibold text-cyan-100">Artifact Registry</div>
              <p className="text-xs text-neutral-500">Structured artifact refs collected from runtime events. Summaries stay compact and ref-based.</p>
            </div>
            <button onClick={() => downloadJson('runtime-artifact-registry.json', artifactRegistry)} disabled={!artifactRegistry.artifacts.length} className="flex items-center gap-2 rounded-lg border border-white/10 bg-black/30 px-3 py-2 text-xs font-semibold text-neutral-300 hover:text-white disabled:cursor-not-allowed disabled:opacity-50"><FileJson size={14} />Export artifact registry</button>
          </div>
          <div className="mb-3 flex flex-wrap gap-2">
            <Badge tone="cyan">unique: {artifactSummary.artifact_count}</Badge>
            <Badge tone={artifactSummary.repeated_count ? 'yellow' : 'neutral'}>repeated: {artifactSummary.repeated_count}</Badge>
            {Object.entries(artifactSummary.step_counts).map(([stepId, count]) => <Badge key={stepId}>{stepId}: {count}</Badge>)}
          </div>
          <div className="space-y-2">
            {artifactRegistry.artifacts.length ? artifactRegistry.artifacts.slice(0, 6).map((artifact) => (
              <div key={artifact.artifact_id} className="rounded-lg border border-white/5 bg-white/[0.02] p-3">
                <div className="mb-1 flex flex-wrap gap-2"><Badge tone="cyan">{artifact.kind}</Badge><Badge>{artifact.step_id}</Badge></div>
                <div className="break-all text-xs text-neutral-300">{artifact.ref}</div>
                <div className="mt-1 text-xs text-neutral-500">{artifact.summary}</div>
              </div>
            )) : <div className="text-xs text-neutral-500">No artifact refs yet. Dispatch or ingest runtime events to populate this registry.</div>}
          </div>
        </div>

        <div className="rounded-xl border border-white/10 bg-black/30 p-4">
          <div className="mb-3 flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between">
            <div>
              <div className="mb-1 text-xs font-semibold text-cyan-100">Controlled Worker Manifest Preview</div>
              <p className="text-xs text-neutral-500">Preview-only manifest. Exporting it does not dispatch work or imply external runtime execution.</p>
            </div>
            <button onClick={() => downloadJson('controlled-worker-manifest-preview.json', controlledManifestPreview)} className="flex items-center gap-2 rounded-lg border border-white/10 bg-black/30 px-3 py-2 text-xs font-semibold text-neutral-300 hover:text-white"><FileJson size={14} />Export manifest</button>
          </div>
          <div className="mb-3 flex flex-wrap gap-2">
            <Badge tone="green">allowlisted</Badge>
            <Badge>{controlledManifestPreview.actions.length} actions</Badge>
            <Badge>write_step_artifact</Badge>
            <Badge>write_manifest_summary</Badge>
          </div>
          <div className="space-y-2">
            {controlledManifestPreview.actions.slice(0, 5).map((action) => (
              <div key={action.action_id} className="rounded-lg border border-white/5 bg-white/[0.02] p-3 text-xs">
                <div className="font-semibold text-neutral-200">{action.action_kind}</div>
                <div className="mt-1 text-neutral-500">{action.action_id}{'step_id' in action && action.step_id ? ` · ${action.step_id}` : ''}{'output_kind' in action && action.output_kind ? ` · ${action.output_kind}` : ''}</div>
              </div>
            ))}
          </div>
        </div>
      </div>

      <div className="mt-4 grid gap-3 xl:grid-cols-2">
        <div className="rounded-xl border border-white/10 bg-black/30 p-4">
          <div className="mb-1 text-xs font-semibold text-cyan-100">External Runtime Mode</div>
          <p className="mb-3 text-xs text-neutral-500">Envelope export is not external execution. Operator-run and direct-run modes remain future integration decisions.</p>
          <div className="flex flex-wrap gap-2">
            <Badge tone="green">current: envelope-only</Badge>
            <Badge tone="yellow">future: operator-run</Badge>
            <Badge tone="red">direct-run unavailable</Badge>
          </div>
          <div className="mt-3 text-xs text-neutral-500">Referenced plans: docs/openhands-real-integration-plan.md and docs/code-agent-real-integration-plan.md.</div>
        </div>

        <div className="rounded-xl border border-white/10 bg-black/30 p-4">
          <div className="mb-3 flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between">
            <div>
              <div className="mb-1 text-xs font-semibold text-cyan-100">Memory / Context Preview</div>
              <p className="text-xs text-neutral-500">Carry-forward preview after review and memory/context hardening. Raw runtime payloads are excluded.</p>
            </div>
            <button onClick={() => downloadJson('memory-context-preview.json', memoryContextPreview)} className="flex items-center gap-2 rounded-lg border border-white/10 bg-black/30 px-3 py-2 text-xs font-semibold text-neutral-300 hover:text-white"><FileJson size={14} />Export memory/context preview</button>
          </div>
          <div className="grid grid-cols-2 gap-2 text-center md:grid-cols-4">
            <div className="rounded-lg border border-white/5 bg-white/[0.02] p-3"><div className="text-xl text-white">{memoryContextPreview.memory_update_packet.accepted_decisions.length}</div><div className="text-[10px] uppercase tracking-widest text-neutral-500">decisions</div></div>
            <div className="rounded-lg border border-white/5 bg-white/[0.02] p-3"><div className="text-xl text-white">{memoryContextPreview.memory_update_packet.runtime_blockers.length}</div><div className="text-[10px] uppercase tracking-widest text-neutral-500">blockers</div></div>
            <div className="rounded-lg border border-white/5 bg-white/[0.02] p-3"><div className="text-xl text-white">{memoryContextPreview.memory_update_packet.artifact_summaries.length}</div><div className="text-[10px] uppercase tracking-widest text-neutral-500">artifacts</div></div>
            <div className="rounded-lg border border-white/5 bg-white/[0.02] p-3"><div className="text-xl text-white">{memoryContextPreview.memory_update_packet.open_questions.length}</div><div className="text-[10px] uppercase tracking-widest text-neutral-500">questions</div></div>
          </div>
          <div className="mt-3 flex flex-wrap gap-2">
            <Badge tone={reviewPreview.release_ready ? 'green' : 'yellow'}>{reviewPreview.release_ready ? 'release ready' : 'follow-up required'}</Badge>
            <Badge>{memoryContextPreview.memory_update_packet.do_not_store.rule_id}</Badge>
          </div>
        </div>
      </div>

      {response && request && (
        <div className="mt-4 rounded-xl border border-white/10 bg-black/30 p-4">
          <div className="mb-3 flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between">
            <div>
              <div className="mb-1 text-xs font-semibold text-cyan-100">Runtime Callback Ingest</div>
              <p className="text-xs text-neutral-500">Simulates later worker callbacks after the initial adapter response. Duplicate callback replay is deduped by event key.</p>
            </div>
            <div className="flex flex-wrap gap-2">
              <button onClick={simulateCallback} className="flex items-center gap-2 rounded-lg border border-cyan-500/30 bg-cyan-950/30 px-3 py-2 text-xs font-semibold text-cyan-200 hover:bg-cyan-900/30">
                <Activity size={14} /> Simulate mock callback
              </button>
              <button onClick={replayLastCallback} disabled={!callbackPayload} className="flex items-center gap-2 rounded-lg border border-white/10 bg-black/30 px-3 py-2 text-xs font-semibold text-neutral-300 hover:text-white disabled:cursor-not-allowed disabled:opacity-50">
                <RotateCcw size={14} /> Replay last callback / dedupe check
              </button>
            </div>
          </div>
          <div className="flex flex-wrap gap-2">
            <Badge tone="cyan">seen keys: {seenEventKeys.length}</Badge>
            <Badge tone="green">accepted last: {lastCallbackAcceptedCount}</Badge>
            <Badge tone={lastCallbackDuplicateCount ? 'yellow' : 'neutral'}>duplicate last: {lastCallbackDuplicateCount}</Badge>
            {callbackPayload && <Badge>{callbackPayload.packet_type}</Badge>}
          </div>
        </div>
      )}

      {(request || response || callbackPayload) && (
        <div className="mt-4 flex flex-wrap gap-2">
          {request && <button onClick={() => downloadJson('runtime-adapter-request.json', request)} className="flex items-center gap-2 rounded-lg border border-white/10 bg-black/30 px-3 py-2 text-xs font-semibold text-neutral-300 hover:text-white"><FileJson size={14} />Export runtime adapter request</button>}
          {response && <button onClick={() => downloadJson('runtime-adapter-response.json', response)} className="flex items-center gap-2 rounded-lg border border-white/10 bg-black/30 px-3 py-2 text-xs font-semibold text-neutral-300 hover:text-white"><FileJson size={14} />Export adapter response</button>}
          {callbackPayload && <button onClick={() => downloadJson('runtime-callback.json', callbackPayload)} className="flex items-center gap-2 rounded-lg border border-white/10 bg-black/30 px-3 py-2 text-xs font-semibold text-neutral-300 hover:text-white"><FileJson size={14} />Export runtime callback</button>}
        </div>
      )}

      <div className="mt-4 grid gap-3 md:grid-cols-2">
        <div className="rounded-xl border border-white/10 bg-black/30 p-4 text-sm text-neutral-400"><Cpu size={16} className="mb-2 text-cyan-400" />Mock provider runs in-process; HTTP provider now uses the panel config for endpoint, timeout, retry and auth boundaries.</div>
        <div className="rounded-xl border border-white/10 bg-black/30 p-4 text-sm text-neutral-400"><Network size={16} className="mb-2 text-cyan-400" />Initial response events and later callback events both update Runner state, while duplicate callback events are ignored.</div>
      </div>
    </section>
  );
}
